verifying DSA signatures in SKE
tlsfuzzer/tlslite-ng pull request #425
Opened 2020-10-07 07:47 UTC by Hedgehog5040

2020-10-07 08:40 UTC, tomato42 requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: all files reviewed, 4 unresolved discussions (waiting on @Hedgehog5040)

___
*[tlslite/keyexchange.py, line 195 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ15iAu32b4gVraqJt7:-MJ15iAu32b4gVraqJt8:b1d8b0r) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/tlslite/keyexchange.py#L195)):*
> ```Python
>         hashBytes = serverKeyExchange.hash(clientRandom, serverRandom)
> ```

don't we have to verify that the signature matches the `hashBytes`?
___
*[tlslite/messages.py, line 1571 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ18Oyt-hpgP6waKGra:-MJ18Oyt-hpgP6waKGrb:b-g6mqmh) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/tlslite/messages.py#L1571)):*
> ```Python
>         if self.cipherSuite in CipherSuite.certAllSuites or \
>                 self.cipherSuite in CipherSuite.ecdheEcdsaSuites or \
>                 self.cipherSuite in CipherSuite.dheDsaSuites:
> ```

technically this is part of the "making DSA signatures in SKE" :) but i'ts fine if it will make writing test cases easier
___
*[unit_tests/test_tlslite_keyexchange.py, line 364 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ196UrB8wYNmsKp39Z:-MJ196UrB8wYNmsKp39_:b-z7psx5) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/unit_tests/test_tlslite_keyexchange.py#L364)):*
> ```Python
>                                                 None)
> 
> class TestServerKeyExchangeDSA(unittest.TestCase):
> ```

1. Negative test case missing, we should have one with malformed signature
2. since in TLS 1.1 and earlier DSA SKEs are special, we should have tests with them too
3. we should also have a test to verify that a SKE message with correct signature will be rejected when we have the hash it used disabled
___
*[unit_tests/test_tlslite_keyexchange.py, line 390 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ1BptPAYITmXfAVQ4Y:-MJ1BptPAYITmXfAVQ4Z:b-5t7yui) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/unit_tests/test_tlslite_keyexchange.py#L390)):*
> ```Python
> 
>     def test_verify_dsa_signature_in_TLS1_2_SHA384(self):
>         skemsg = a2b_hex("0001b90080b10b8f96a080e01dde92de5eae5d54ec52c99fbcfb06a3c69a6a9dca52d23b616073e28675a23d189838ef1e2ee652c013ecb4aea906112324975c3cd49b83bfaccbdd7d90c4bd7098488e9c219a73724effd6fae5644738faa31a4ff55bccc0a151af5f0dc8b4bd45bf37df365c1a65e68cfda76d4da708df1fb2bc2e4a43710080a4d1cbd5c3fd34126765a442efb99905f8104dd258ac507fd6406cff14266d31266fea1e5c41564b777e690f5504f213160217b4b01b886a5e91547f9e2749f4d7fbd7d3b9a92ee1909d0d2263f80a76a6a24c087a091f531dbf0a0169b6a28ad662a4d18e73afa32d779d5918d08bc8858f4dcef97c2a24855e6eeb22b3b2e500807c4707b1ebadeafb719be08d627b90e2cd07ccf91aacd62b8803399d425766e2d87a82824edf2a507feb56ed417cf452600749c70d4cf7f5cc22a074d63ea6e39871a8613e36a717d5d1672407ae6761d1527821ee6ab4f00c92ec42ec0da07bcaa33b287225202d5bfbafc377c41a42e4cacf80c978390ecd98c3316021c79d0402002f302d0215008ed71b80e574d68ae9685ba36b191671dd7d9f9402147cc8b92935fc9a98332676830abeabe2a3b25f90")
> ```

please split up this line; while we have monitors that can fit more than 80 columns, when resolving merge conflicts it's necessary to look at 240 columns of text
___
*[unit_tests/test_tlslite_messages.py, line 2394 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ1ADhx1p4I7yU75jOA:-MJ1ADhx1p4I7yU75jOB:b-v5im3z) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/unit_tests/test_tlslite_messages.py#L2394)):*
> ```Python
>                                    b'\xbaQ\xedo\xa13Z\xa5}'))
> 
>     def test_hash_with_dsa_in_tls1_1(self):
> ```

we should also have unit tests for serialising and de-serialising DHE DSS SKEs, similar to `test_parser_with_ECDH` and `test_createECDH`


<!-- Sent from Reviewable.io -->

2020-10-19 20:57 UTC, tomato42 reviewed
:( sorry, I don't see anything obviously wrong, I'll need to run this code tomorrow and check what's what

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-:-MK1dWkJ9SnwQPbXR3Mc:b-c9qw1g)* status: all files reviewed, 2 unresolved discussions (waiting on @Hedgehog5040)



<!-- Sent from Reviewable.io -->

2020-10-20 11:59 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: all files reviewed, 5 unresolved discussions (waiting on @Hedgehog5040)

___
*[unit_tests/test_tlslite_keyexchange.py, line 401 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MK4roka34BlLaiS1qGw:-MK4rokbAGU-nyNX1SBR:b-mji6ww) ([raw file](https://github.com/tomato42/tlslite-ng/blob/410ae9076a3c22dcbd29d0c0e4926e6ec2de9b0c/unit_tests/test_tlslite_keyexchange.py#L401)):*
> ```Python
>                 "ad6b382013b6bc6ed3044fbbab0b2f9d26bcce3bae0402002f302d021500b5"
>                 "dd272c8ca096c5d5ea999ea0d369aecd492441021440bd8a5f340991b41c17"
>                 "f9d0724f3ca8ded4f5d7")
> ```

it's weird, when I extract the params and signature, save them to file and try to verify with openssl, the verification is successful
but python_dsakey can't verify it, at the same time, I can make and verify signatures with python_dsakey and they do verify with openssl...

At this point I'd suggest adding more test vectors to the DSA implementation
___
*[unit_tests/test_tlslite_messages.py, line 2397 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MK4k--rA37pf1bunoKS:-MK4k--rA37pf1bunoKT:bbp6y5) ([raw file](https://github.com/tomato42/tlslite-ng/blob/410ae9076a3c22dcbd29d0c0e4926e6ec2de9b0c/unit_tests/test_tlslite_messages.py#L2397)):*
> ```Python
>         ske = ServerKeyExchange(
>                 CipherSuite.TLS_DHE_DSS_WITH_AES_128_CBC_SHA256,
>                 (3, 1))
> ```

(3, 1) == TLS 1.0; but the ciphersuite is TLS 1.2 only and the hashAlg is set below
___
*[unit_tests/test_tlslite_messages.py, line 2405 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MK4m7cn6uGMwCJFbLbh:-MK4m7cpBJpv1OSq5Gin:bspgp7l) ([raw file](https://github.com/tomato42/tlslite-ng/blob/410ae9076a3c22dcbd29d0c0e4926e6ec2de9b0c/unit_tests/test_tlslite_messages.py#L2405)):*
> ```Python
> 
>         self.assertEqual(hash1,
>                          bytearray(b'\x4a\x95\x6f\x85\x4e\xed\x6c\x5f\x84\x17\x92\xd6\xa8\x8d\x8c\xd7\xb2\xd0\xf7\xfb'))
> ```

this is a hash of this SKE with SHA1, not SHA256


<!-- Sent from Reviewable.io -->

2020-10-20 15:23 UTC, tomato42 commented
I remember that there were some interoperability issues with TLS 1.2... maybe try two things: capture SKE in TLS 1.1 or TLS 1.0, and one with forced SHA-1 signatures in TLSv1.2

2020-10-23 09:05 UTC, tomato42 requested changes
the failures on python2.6 need fixes, looks like some call is missing `compatHMAC()`

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-:-MKJgdgJ03q4P0zKnvRR:b-obf8ow)* status: all files reviewed, 7 unresolved discussions (waiting on @Hedgehog5040)

___
*[tlslite/utils/python_dsakey.py, line 16 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJdb8y8SotjPNClscK:-MKJdb8z5dwlR54j9Av_:b88u9my) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/tlslite/utils/python_dsakey.py#L16)):*
> ```Python
> 
> from .dsakey import DSAKey
> import math
> ```

unused import
___
*[tlslite/utils/python_dsakey.py, line 84 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJe2LOBxl1IZPOS6oB:-MKJe2LOBxl1IZPOS6oC:b-o9clm5) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/tlslite/utils/python_dsakey.py#L84)):*
> ```Python
>         N = int(numBits(self.q) / 8)
>         hashData = hashData[:N]
>         digest = bytesToNumber(hashData)
> ```

what if bit length of q isn't a multiple of 8?
`getRandomPrime` won't generate ones like this, but other implementations can
___
*[unit_tests/test_tlslite_keyexchange.py, line 386 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJfOP8BdrEfIxhUnjL:-MKJfOP8BdrEfIxhUnjM:bxo9nz9) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/unit_tests/test_tlslite_keyexchange.py#L386)):*
> ```Python
>         cls.x509 = x509
> 
>     def test_verify_dsa_signature_in_TLS1_1_SHA1(self):
> ```

technically, this is TLS 1.0 (`(3, 0)`==SSL3, `(3, 1)` == TLS1.0, `(3, 2)`==TLS1.1)
___
*[unit_tests/test_tlslite_keyexchange.py, line 419 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJfKK09ugbEDnExxYB:-MKJfKK12ksOXpMTmU9h:bj0w1tt) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/unit_tests/test_tlslite_keyexchange.py#L419)):*
> ```Python
>                                             server_random,
>                                             [(HashAlgorithm.sha256,
>                                               SignatureAlgorithm.dsa)])
> ```

for TLS 1.0 we should be able to skip the allowed algorithms here... or do I remember the verifyServerKeyExchange code wrong?


<!-- Sent from Reviewable.io -->

2020-10-23 14:22 UTC, Hedgehog5040 commented
___
*[tlslite/utils/python_dsakey.py, line 16 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJdb8y8SotjPNClscK:-MKKpc1b2-e2bNuq5Uc5:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/tlslite/utils/python_dsakey.py#L16)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

unused import
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-30 16:00 UTC, Hedgehog5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @Hedgehog5040 and @tomato42)

___
*[tlslite/utils/python_dsakey.py, line 84 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJe2LOBxl1IZPOS6oB:-MKuDNe_2X656QbVIe97:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/tlslite/utils/python_dsakey.py#L84)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

what if bit length of q isn't a multiple of 8?
`getRandomPrime` won't generate ones like this, but other implementations can
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_keyexchange.py, line 401 at r2](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MK4roka34BlLaiS1qGw:-MKKncML2xdfO-gMmmvX:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/410ae9076a3c22dcbd29d0c0e4926e6ec2de9b0c/unit_tests/test_tlslite_keyexchange.py#L401)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

it's weird, when I extract the params and signature, save them to file and try to verify with openssl, the verification is successful
but python_dsakey can't verify it, at the same time, I can make and verify signatures with python_dsakey and they do verify with openssl...

At this point I'd suggest adding more test vectors to the DSA implementation
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_keyexchange.py, line 386 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJfOP8BdrEfIxhUnjL:-MKKndxF0cE_X6htAR11:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/unit_tests/test_tlslite_keyexchange.py#L386)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

technically, this is TLS 1.0 (`(3, 0)`==SSL3, `(3, 1)` == TLS1.0, `(3, 2)`==TLS1.1)
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_keyexchange.py, line 419 at r3](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MKJfKK09ugbEDnExxYB:-MKKncfx4IS__6tqi-ii:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/bcf080b646738e8a0b8c11bbcb53c8704767a09e/unit_tests/test_tlslite_keyexchange.py#L419)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

for TLS 1.0 we should be able to skip the allowed algorithms here... or do I remember the verifyServerKeyExchange code wrong?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-30 16:27 UTC, Hedgehog5040 commented
___
*[unit_tests/test_tlslite_keyexchange.py, line 364 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ196UrB8wYNmsKp39Z:-MKuJCTH-EzNqbYlH04N:bwguan2) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/unit_tests/test_tlslite_keyexchange.py#L364)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

1. Negative test case missing, we should have one with malformed signature
2. since in TLS 1.1 and earlier DSA SKEs are special, we should have tests with them too
3. we should also have a test to verify that a SKE message with correct signature will be rejected when we have the hash it used disabled
</blockquote></details>

What do you mean by hash disabled?


<!-- Sent from Reviewable.io -->

2020-11-03 14:44 UTC, tomato42 commented
@Hedgehog5040 the CI failed...

2020-11-11 12:31 UTC, tomato42 requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: all files reviewed, 7 unresolved discussions (waiting on @Hedgehog5040 and @tomato42)

___
*[tlslite/utils/python_dsakey.py, line 85 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MLrGNDw6T0Bm-48kyUo:-MLrGNDx9dJdvFyZ65zU:b1yobbf) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a81a94b0bd10a2825d962f0f415c49165fa2dd0b/tlslite/utils/python_dsakey.py#L85)):*
> ```Python
>         digest = bytesToNumber(hashData)
>         if N < digest_len:
>             digest = (digest & (~0 << (digest_len - N))) >> (digest_len - N)
> ```

wouldn't `digest >>= digest_len - N` be simpler? why AND it against `~0`?
___
*[tlslite/utils/python_dsakey.py, line 99 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MLrH5lP3XXX4q9-rJ0r:-MLrH5lQBeHbxL9fjCjf:bse7rt7) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a81a94b0bd10a2825d962f0f415c49165fa2dd0b/tlslite/utils/python_dsakey.py#L99)):*
> ```Python
> 
>         if N < digest_len:
>             digest = (digest & (~0 << (digest_len - N))) >> (digest_len - N)
> ```

same here, `digest >>= digest_len -N` would be simpler, wouldn't it?


<!-- Sent from Reviewable.io -->

2020-11-13 16:02 UTC, Hedgehog5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: 5 of 10 files reviewed, 7 unresolved discussions (waiting on @Hedgehog5040 and @tomato42)

___
*[tlslite/utils/python_dsakey.py, line 85 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MLrGNDw6T0Bm-48kyUo:-MM0lil_AeAWgMRApZbL:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a81a94b0bd10a2825d962f0f415c49165fa2dd0b/tlslite/utils/python_dsakey.py#L85)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

wouldn't `digest >>= digest_len - N` be simpler? why AND it against `~0`?
</blockquote></details>

Done.
___
*[tlslite/utils/python_dsakey.py, line 99 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MLrH5lP3XXX4q9-rJ0r:-MM0lkPg39aF_K6y04Pw:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a81a94b0bd10a2825d962f0f415c49165fa2dd0b/tlslite/utils/python_dsakey.py#L99)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here, `digest >>= digest_len -N` would be simpler, wouldn't it?
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_keyexchange.py, line 364 at r1](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MJ196UrB8wYNmsKp39Z:-MM1Kupp07uwXN9L_Yzq:b-896fix) ([raw file](https://github.com/tomato42/tlslite-ng/blob/551139b0f39ecdb02abda90bab7b85d547a7e3f5/unit_tests/test_tlslite_keyexchange.py#L364)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

Not passed in as one of the valid ones

I've noticed that we'll also need changes to HandshakeSettings, to have something like `rsaSigHashes` and `ecdsaSigHashes` for DSA 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-13 20:37 UTC, tomato42 requested changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: all files reviewed, 8 unresolved discussions (waiting on @Hedgehog5040)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2JEig94Ux4YF3pOUS:-MM2JEig94Ux4YF3pOUT:b-o17nkg) (no related file):*
do we have a test case to verify we can actually negotiate DSA? I don't see one in `tests/tlstest.py`... or the implementation is still limited to just verifying signatures, not making them?

---
___
*[tlslite/tlsconnection.py, line 4429 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2GzjB4We2PHIymJjM:-MM2GzjB4We2PHIymJjN:bjgfizy) ([raw file](https://github.com/tomato42/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/tlsconnection.py#L4429)):*
> ```
> is "dsa"
> ```
`is` should not be used with literals, use `==`
___
*[tlslite/tlsconnection.py, line 4432 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2HEaJ0LsT9EmKzBlZ:-MM2HEaJ0LsT9EmKzBl_:bmimd2y) ([raw file](https://github.com/tomato42/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/tlsconnection.py#L4432)):*
> ```Python
>             for schemeName in settings.dsaSigHashes:
>                 if version > (3, 3):
>                     continue;
> ```

nit: leftover `;`
___
*[tlslite/tlsconnection.py, line 4434 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2HQ0t8IwQ3cUFK7QR:-MM2HQ0u1j6tHbvG0U1T:bngze1c) ([raw file](https://github.com/tomato42/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/tlsconnection.py#L4434)):*
> ```Python
>                     continue;
> 
>                 if version < (3, 3) and hashName != "sha1":
> ```

do we reach this code in TLS 1.1? when?
___
*[tlslite/tlsconnection.py, line 4435 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2HIy94e8fQeqJgzO3:-MM2HIy94e8fQeqJgzO4:b-jw7agg) ([raw file](https://github.com/tomato42/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/tlsconnection.py#L4435)):*
> ```Python
> 
>                 if version < (3, 3) and hashName != "sha1":
>                     continue;
> ```

nit: leftover`;`
___
*[tlslite/utils/python_dsakey.py, line 85 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MLrGNDw6T0Bm-48kyUo:-MM2IlTq9gmTQyWEBie6:b-1qc699) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a81a94b0bd10a2825d962f0f415c49165fa2dd0b/tlslite/utils/python_dsakey.py#L85)):*
<details><summary><i>Previously, Hedgehog5040 (Frantisek Krenzelok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see this updated code...
___
*[tlslite/utils/python_dsakey.py, line 99 at r4](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MLrH5lP3XXX4q9-rJ0r:-MM2Irwn-GZGEspx9Sj7:b-2guby3) ([raw file](https://github.com/tomato42/tlslite-ng/blob/a81a94b0bd10a2825d962f0f415c49165fa2dd0b/tlslite/utils/python_dsakey.py#L99)):*
<details><summary><i>Previously, Hedgehog5040 (Frantisek Krenzelok) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same here
___
*[tlslite/utils/python_dsakey.py, line 101 at r5](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2J00G6ZUaKWpX0NwF:-MM2J00G6ZUaKWpX0NwG:bsbov9t) ([raw file](https://github.com/tomato42/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/utils/python_dsakey.py#L101)):*
> ```Python
>             digest = (digest & (~0 << (digest_len - N))) >> (digest_len - N)
> 
>         signature = bytes(signature)    #fix for python 2.6
> ```

I think we want `utils.compat.compatHMAC()` here


<!-- Sent from Reviewable.io -->

2020-11-13 20:46 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tomato42/tlslite-ng/425)* status: all files reviewed, 9 unresolved discussions (waiting on @Hedgehog5040)

*[a discussion](https://reviewable.io/reviews/tomato42/tlslite-ng/425#-MM2Ltam8VTJc8kTYPGw:-MM2Ltam8VTJc8kTYPGx:b-l2wuf0) (no related file):*
remember to rebase on top of master

---


<!-- Sent from Reviewable.io -->

2020-11-19 10:21 UTC, Hedgehog5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @Hedgehog5040 and @tomato42)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MM2Ltam8VTJc8kTYPGw:-MMV0SxS4ZXSt7HwDi7d:b-896fix) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

remember to rebase on top of master
</blockquote></details>

Done.

---
___
*[tlslite/tlsconnection.py, line 4429 at r5](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MM2GzjB4We2PHIymJjM:-MMV0UVW3brHpnCzjr8F:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/tlsconnection.py#L4429)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

> ```
> is "dsa"
> ```
`is` should not be used with literals, use `==`
</blockquote></details>

Done.
___
*[tlslite/tlsconnection.py, line 4434 at r5](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MM2HQ0t8IwQ3cUFK7QR:-MMUWFlgEqpiOx6kESas:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/tlsconnection.py#L4434)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

do we reach this code in TLS 1.1? when?
</blockquote></details>

Done.
___
*[tlslite/utils/python_dsakey.py, line 101 at r5](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MM2J00G6ZUaKWpX0NwF:-MMUekhp35k8Biremw-y:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/866e3445272ec45d227dfb1d083dc1cf8eb7f96c/tlslite/utils/python_dsakey.py#L101)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I think we want `utils.compat.compatHMAC()` here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-02 09:24 UTC, tomato42 reviewed
So to reiterate, the scope is:
 * DSA support in ServerKeyExchange only (without client certificates), with tlslite-ng working as both client and server
 * working in TLS 1.0, TLS 1.1 and TLS 1.2
 * works with different signature algorithms in TLS 1.2 (at least sha-1, sha-256, sha-384 and sha512)
 * interoperates with at least 1 or 2 different implementations both as client and server

> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-:-MNXk0mcAxNRSv6jfXOo:b-v3jyeg)* status: all files reviewed, 9 unresolved discussions (waiting on @Hedgehog5040)



<!-- Sent from Reviewable.io -->

2020-12-09 11:14 UTC, tomato42 requested changes
> Reviewed 1 of 3 files at r7, 6 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: all files reviewed, 14 unresolved discussions (waiting on @Hedgehog5040)

___
*[tlslite/constants.py, line 1335 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MO6B6Zt1ufmWhs-MtKv:-MO6B6Zt1ufmWhs-MtKw:b-3cclfq) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/d57e316fe8d3e0009d26c51a638c9ef0b057065d/tlslite/constants.py#L1335)):*
> ```Python
>             keyExchangeSuites += CipherSuite.srpCertSuites
>         if "srp_sha_dsa" in keyExchangeNames:
>             keyExchangeSuites += CipherSuite.srpDsaSuites
> ```

if they're unsupported, they shouldn't be added here
___
*[tlslite/keyexchange.py, line 113 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MO6BjPtEAmMkM2YWfFB:-MO6BjPtEAmMkM2YWfFC:b-2nv4ux) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/d57e316fe8d3e0009d26c51a638c9ef0b057065d/tlslite/keyexchange.py#L113)):*
> ```Python
>             serverKeyExchange.signAlg = SignatureAlgorithm.dsa
>             serverKeyExchange.hashAlg = getattr(HashAlgorithm, sigHash)
>             keyType = 'rsa'
> ```

this is a dsa method...
___
*[unit_tests/test_tlslite_keyexchange.py, line 278 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MO6CAn6Bd2eYmuut1HC:-MO6CAn6Bd2eYmuut1HD:bvzqv5y) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/d57e316fe8d3e0009d26c51a638c9ef0b057065d/unit_tests/test_tlslite_keyexchange.py#L278)):*
> ```Python
> 
>     def test_signServerKeyExchange_with_sha1_dsa_in_TLS1_2:
> ```

empty test case


<!-- Sent from Reviewable.io -->

2020-12-11 09:23 UTC, Hedgehog5040 commented
___
*[tlslite/handshakesettings.py, line 532 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MM1KdTWf8l3iYlKBGSm-r6-532:-MOG66Fx9Z9wKrdEBbHU:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/9c1cb125a720d332099cdb601af327c2141f0989/tlslite/handshakesettings.py#L532)):*
<details><summary><i>Previously, codeclimate[bot] wrote…</i></summary><blockquote>

Multiple spaces after keyword
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 15:57 UTC, tomato42 commented
please remember to rebase when submitting a new version, as we switched CI runners

2021-01-28 17:49 UTC, tomato42 commented
Look like the py3.8 run fails because of https://github.com/codeclimate/test-reporter/issues/453, could you create a new PR that runs the codeclimate submission based on the environment var being set or not?

2021-01-29 17:04 UTC, tomato42 commented
ok, should be fixed now, please try rebasing

2021-02-11 18:52 UTC, tomato42 commented
```
FileNotFoundError: [Errno 2] No such file or directory: 'tests/serverDSACert.pem'
```
you need to add those certificates in the same commit as you add the tests

2021-02-18 13:57 UTC, Hedgehog5040 commented
*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MM2JEig94Ux4YF3pOUS:-MTpQWxb2TZDr2Ifx6Ch:b-896fix) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

do we have a test case to verify we can actually negotiate DSA? I don't see one in `tests/tlstest.py`... or the implementation is still limited to just verifying signatures, not making them?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-02-18 14:00 UTC, Hedgehog5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: 5 of 18 files reviewed, 15 unresolved discussions (waiting on @codeclimate[bot] and @tomato42)

___
*[tlslite/handshakesettings.py, line 514 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MOG65Hs3SV787CJoLUi:-MOG65Ht7MKt3sLhXJJE:b-ed1609) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0812ed60860fa61a6573b2c0e18771414958f46d/tlslite/handshakesettings.py#L514)):*
> ```
>                 not other.dsaSigHashes and o
> ```


<!-- Sent from Reviewable.io -->

2021-02-18 15:37 UTC, tomato42 requested changes
> Reviewed 1 of 3 files at r9, 6 of 9 files at r10, 6 of 6 files at r11.
> Dismissed @codeclimate[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: all files reviewed, 12 unresolved discussions (waiting on @codeclimate[bot] and @Hedgehog5040)

___
*[tests/tlstest.py, line 852 at r11](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTpkpajETvRkNz1XwMV:-MTpkpajETvRkNz1XwMW:bia1wtc) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/fb5935b1a8ff6f95aec51f72cf86eb96184c0f3d/tests/tlstest.py#L852)):*
> ```Python
>     test_no += 1
> 
>     print("Test {0} - good X.509 DSA, SSLv3".format(test_no))
> ```

could you add TLS 1.2? since the hash algorithm is negotiated there, the handshake is different...
___
*[tlslite/handshakesettings.py, line 526 at r10](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTph6qY-cEo0XR9ewaP:-MTph6qY-cEo0XR9ewaQ:b-g89gw9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f79b5d4a1d5af30788b36e9bf364f1276bb9468d/tlslite/handshakesettings.py#L526)):*
> ```Python
> 
>         unknownSigHash = not_matching(other.dsaSigHashes,
>                                       ALL_RSA_SIGNATURE_HASHES)
> ```

shouldn't this be `DSA_SIGNATURE_HASHES`? we don't want to support MD5 signatures for DSA
___
*[tlslite/tlsconnection.py, line 1868 at r11](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTplTWt2XSeOErViY1g:-MTplTWu0liHQzquSMWh:bjgzmrv) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/fb5935b1a8ff6f95aec51f72cf86eb96184c0f3d/tlslite/tlsconnection.py#L1868)):*
> ```Python
>         else:
>             # for RSA and DSA keys
>             if len(publicKey) < settings.minKeySize:
> ```

this is correct, but we should update the minKeySize and maxKeySize description to include reference to DSA
___
*[unit_tests/test_tlslite_keyexchange.py, line 361 at r10](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTpjSCK1KRl-sSyoSit:-MTpjSCK1KRl-sSyoSiu:b-j8rtx9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f79b5d4a1d5af30788b36e9bf364f1276bb9468d/unit_tests/test_tlslite_keyexchange.py#L361)):*
> ```Python
>                 return_value=bytearray(b'wrong'))
>             keyExchange.signServerKeyExchange(server_key_exchange)
> """
> ```

that's a commented out test case


<!-- Sent from Reviewable.io -->

2021-02-18 16:00 UTC, Hedgehog5040 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: 15 of 18 files reviewed, 11 unresolved discussions (waiting on @codeclimate[bot] and @tomato42)

___
*[tests/tlstest.py, line 852 at r11](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTpkpajETvRkNz1XwMV:-MTprYVj-VeOYa7o6F4T:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/fb5935b1a8ff6f95aec51f72cf86eb96184c0f3d/tests/tlstest.py#L852)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

could you add TLS 1.2? since the hash algorithm is negotiated there, the handshake is different...
</blockquote></details>

Done.
___
*[tlslite/handshakesettings.py, line 526 at r10](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTph6qY-cEo0XR9ewaP:-MTprcBiCjfXj7jsOwVw:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f79b5d4a1d5af30788b36e9bf364f1276bb9468d/tlslite/handshakesettings.py#L526)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

shouldn't this be `DSA_SIGNATURE_HASHES`? we don't want to support MD5 signatures for DSA
</blockquote></details>

Done.
___
*[tlslite/tlsconnection.py, line 1868 at r11](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTplTWt2XSeOErViY1g:-MTpre-0Azor9mDuuBW3:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/fb5935b1a8ff6f95aec51f72cf86eb96184c0f3d/tlslite/tlsconnection.py#L1868)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this is correct, but we should update the minKeySize and maxKeySize description to include reference to DSA
</blockquote></details>

Done.
___
*[unit_tests/test_tlslite_keyexchange.py, line 361 at r10](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTpjSCK1KRl-sSyoSit:-MTprfJq6nktlohXXvD1:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f79b5d4a1d5af30788b36e9bf364f1276bb9468d/unit_tests/test_tlslite_keyexchange.py#L361)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

that's a commented out test case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 16:32 UTC, tomato42 requested changes
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: all files reviewed, 8 unresolved discussions (waiting on @codeclimate[bot] and @Hedgehog5040)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTpyAr9C4ZoslnHksJz:-MTpyArAEegKtIchajOX:b-3z9iy4) (no related file):*
so it looks good, I can use openssl client and get a connection with DSA cert on tlslite-ng side, but it doesn't work with TLS 1.0 or with TLS 1.2 and SHA-1 signatures

i.e.
```
openssl s_client -connect localhost:4433 -tls1_2 -cipher aDSS -sigalgs SHA256+DSA
```
works
but
```
openssl s_client -connect localhost:4433 -tls1_2 -cipher aDSS -sigalgs SHA1+DSA
```
and
```
openssl s_client -connect localhost:4433 -tls1 -cipher aDSS
```
don't

---


<!-- Sent from Reviewable.io -->

2021-02-18 16:39 UTC, tomato42 approved these changes
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425)* status: all files reviewed, 7 unresolved discussions (waiting on @codeclimate[bot])

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/425#-MTpyAr9C4ZoslnHksJz:-MTq-aoE-Sd-naV49lwQ:b-ulisn2) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

so it looks good, I can use openssl client and get a connection with DSA cert on tlslite-ng side, but it doesn't work with TLS 1.0 or with TLS 1.2 and SHA-1 signatures

i.e.
```
openssl s_client -connect localhost:4433 -tls1_2 -cipher aDSS -sigalgs SHA256+DSA
```
works
but
```
openssl s_client -connect localhost:4433 -tls1_2 -cipher aDSS -sigalgs SHA1+DSA
```
and
```
openssl s_client -connect localhost:4433 -tls1 -cipher aDSS
```
don't
</blockquote></details>

scratch that, with `master` I need to specify `:@SECLEVEL=0` for SHA-1 to work

---


<!-- Sent from Reviewable.io -->

2021-02-18 16:53 UTC, tomato42 commented
Looks good, thank you!

2021-02-18 16:54 UTC, merged