Draft: add support for RFC 8879 TLS Certificate Compression
tlsfuzzer/tlslite-ng pull request #484
Opened 2022-10-11 12:59 UTC by t184256

I'm sketching up RFC 8879 TLS Certificate Compression support. My intent is to use it with tlsfuzzer to test gnutls' implementation of it.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)

2022-10-17 12:05 UTC, tomato42 requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 9 unresolved discussions (waiting on @t184256)

___
*[`tlslite/messages.py` line 1243 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_mi3h0hQARH84AMt7:-NE_mi3h0hQARH84AMt8:bo1wx96) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1243)):*
> ```Python
> 
> 
> class CompressedCertificate(Certificate):
> ```

Why it's a child class of Certificate?
___
*[`tlslite/messages.py` line 1246 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_lurLDpG0CnBAvFuK:-NE_lurLDpG0CnBAvFuL:b-jl9sez) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1246)):*
> ```Python
>     def __init__(self, certificateType, version=(3, 4),
>                  algorithm=CertificateCompressionAlgorithm.zlib):
>         assert version > (3, 3)  # RFC 8879 is TLS 1.3+ only
> ```

1. That's not how in tlslite-ng the limitation of protocol version is handled
2. this means it will not be usable for tlsfuzzer, to test that it ineed is ignored when used in TLS 1.2 and earlier
3. the `version` in messages is generally used when the format of the message changes between protocol versions; here there's just one format of the message...
___
*[`tlslite/messages.py` line 1248 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_mnae8f7rTjIUgkEi:-NE_mnae8f7rTjIUgkEj:b-jk8krm) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1248)):*
> ```Python
>         assert version > (3, 3)  # RFC 8879 is TLS 1.3+ only
>         super(CompressedCertificate, self).__init__(certificateType, version)
>         HandshakeMsg.__init__(self, HandshakeType.compressed_certificate)
> ```

to me it shows that using Certificate as parent class is a bad idea...
___
*[`tlslite/messages.py` line 1253 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_n29Y4zJ7HdjzSQtt:-NE_n29Y4zJ7HdjzSQtu:bnj7hl0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1253)):*
> ```Python
> 
>     def parse(self, parser):
>         assert self.version > (3, 3)  # RFC 8879 is TLS 1.3+ only
> ```

same as above
___
*[`tlslite/messages.py` line 1256 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_o5eo8G_lbsK0uBTa:-NE_o5eo8G_lbsK0uBTb:btk35ku) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1256)):*
> ```Python
> 
>         # FIXME: why am I peeling length here? is this the right place?
>         inner_parser = Parser(parser.getVarBytes(3))
> ```

it should be startLengthCheck(3)
___
*[`tlslite/messages.py` line 1282 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_n4jTEChwekfYvtcx:-NE_n4jTEChwekfYvtcy:bnj7hl0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1282)):*
> ```Python
> 
>     def write(self):
>         assert self.version > (3, 3)  # RFC 8879 is TLS 1.3+ only
> ```

same as above
___
*[`tlslite/messages.py` line 1301 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_n5sl60MCj5vpmRVn:-NE_n5sl60MCj5vpmRVo:bnj7hl0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1301)):*
> ```Python
> 
>     def __repr__(self):
>         assert self.version > (3, 3)  # RFC 8879 is TLS 1.3+ only
> ```

same as above
___
*[`tlslite/tlsconnection.py` line 4117 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_opX-4iZsUUEDxRKw:-NE_opX-4iZsUUEDxRKx:b-cuytuq) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/tlsconnection.py#L4117)):*
> ```Python
>             if self.version == (3,0):
>                 handshake_types = (HandshakeType.certificate,
>                                    HandshakeType.compressed_certificate)
> ```

this is specifically parsing for SSL3.0, we don't want to support this message there...
___
*[`tlslite/tlsconnection.py` line 4142 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_p84z-mA5nOfaGQ09:-NE_p84z-mA5nOfaGQ0A:bz2qdq4) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/tlsconnection.py#L4142)):*
> ```Python
>             elif self.version in ((3,1), (3,2), (3,3)):
>                 handshake_types = (HandshakeType.certificate,
>                                    HandshakeType.compressed_certificate)
> ```

same here, this is for parsing TLS 1.0, 1.1 and 1.2, for which compressed_certificate is not permitted


<!-- Sent from Reviewable.io -->

2022-10-19 09:58 UTC, t184256 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: 3 of 6 files reviewed, 9 unresolved discussions (waiting on @tomato42)

___
*[`tlslite/messages.py` line 1243 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_mi3h0hQARH84AMt7:-NEjerEdD10p0KhRP3xx:bs1lf2h) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1243)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

Why it's a child class of Certificate?
</blockquote></details>

Replaced with encapsulation.
___
*[`tlslite/messages.py` line 1246 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_lurLDpG0CnBAvFuK:-NEjex5r5n3G2xrBXJtQ:bss4a2b) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1246)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

1. That's not how in tlslite-ng the limitation of protocol version is handled
2. this means it will not be usable for tlsfuzzer, to test that it ineed is ignored when used in TLS 1.2 and earlier
3. the `version` in messages is generally used when the format of the message changes between protocol versions; here there's just one format of the message...
</blockquote></details>

Removed.
___
*[`tlslite/messages.py` line 1248 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_mnae8f7rTjIUgkEi:-NEjezgF5_hVA0me6dBP:bs1lf2h) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1248)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

to me it shows that using Certificate as parent class is a bad idea...
</blockquote></details>

Replaced with encapsulation.
___
*[`tlslite/messages.py` line 1253 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_n29Y4zJ7HdjzSQtt:-NEjf0P4DGcEg35St8Cl:bss4a2b) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1253)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Removed.
___
*[`tlslite/messages.py` line 1256 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_o5eo8G_lbsK0uBTa:-NEjf1wj9TeUBXimrpWB:b-29k0sw) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1256)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

it should be startLengthCheck(3)
</blockquote></details>

Used startLengthCheck.
___
*[`tlslite/messages.py` line 1282 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_n4jTEChwekfYvtcx:-NEjfF0_7mAXtEuSphay:bss4a2b) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1282)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Removed.
___
*[`tlslite/messages.py` line 1301 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_n5sl60MCj5vpmRVn:-NEjfGKa3XPClordylgn:bss4a2b) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/messages.py#L1301)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Removed.
___
*[`tlslite/tlsconnection.py` line 4117 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_opX-4iZsUUEDxRKw:-NEjfI9o0CMtQIU8MrPe:bp3aow6) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/tlsconnection.py#L4117)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this is specifically parsing for SSL3.0, we don't want to support this message there...
</blockquote></details>

Reverted.
___
*[`tlslite/tlsconnection.py` line 4142 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NE_p84z-mA5nOfaGQ09:-NEjfJDE9RGTsW8sdibB:bp3aow6) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/460ecce0e76be9689bb14bb704be9b46cba45141/tlslite/tlsconnection.py#L4142)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here, this is for parsing TLS 1.0, 1.1 and 1.2, for which compressed_certificate is not permitted
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2022-10-19 16:15 UTC, tomato42 requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 2 unresolved discussions (waiting on @t184256)

___
*[`tlslite/messages.py` line 1292 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEkqdpaBZd_TusMNK9s:-NEkqdpb81kYxTzrg0rr:b7h5ltl) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0ade5648bfa92df5f7134d62a783cb2b1c599204/tlslite/messages.py#L1292)):*
> ```Python
>         self.algorithm = parser.get(2)
>         self.uncompressed_length = parser.get(3)
>         compressed_certificate_msg = parser.getFixBytes(parser.get(3))
> ```

why not `getVarBytes(3)`?
___
*[`tlslite/messages.py` line 1296 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEkqyHFAuzDp09YI0bf:-NEkqyHFAuzDp09YI0bg:bur7k48) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0ade5648bfa92df5f7134d62a783cb2b1c599204/tlslite/messages.py#L1296)):*
> ```Python
> 
>         if self.algorithm == CertificateCompressionAlgorithm.zlib:
>             import zlib
> ```

isn't `zlib` built-in, thus, should always be present?


<!-- Sent from Reviewable.io -->

2022-10-19 16:18 UTC, t184256 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[`tlslite/messages.py` line 1296 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEkqyHFAuzDp09YI0bf:-NEl166i0Nel_tjAhPQ_:b-4uxfwu) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0ade5648bfa92df5f7134d62a783cb2b1c599204/tlslite/messages.py#L1296)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

isn't `zlib` built-in, thus, should always be present?
</blockquote></details>

It is. I've put it here to only import as needed and prevent exposing it as tlslite.messages.zlib. Do you want it as an import on the top level?


<!-- Sent from Reviewable.io -->

2022-10-20 09:40 UTC, tomato42 requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 2 unresolved discussions (waiting on @t184256)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEokFa80Gj-4wqZViOH:-NEokFa80Gj-4wqZViOI:b-nvq1l3) (no related file):*
So now we're missing integration with HandshakeSettings, sending the extension, and sending of the compressed cert if peer advertised support for compression...

___
___
*[`tlslite/messages.py` line 1296 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEkqyHFAuzDp09YI0bf:-NEoilOd3vVHWDm9iZy4:b-wagq1v) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0ade5648bfa92df5f7134d62a783cb2b1c599204/tlslite/messages.py#L1296)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

It is. I've put it here to only import as needed and prevent exposing it as tlslite.messages.zlib. Do you want it as an import on the top level?
</blockquote></details>

hmm, while true, I don't think we generally gain anything by importing it locally, while losing on readability, by not having all imports in one place, as is the common practice and a PEP8 recommendation...


<!-- Sent from Reviewable.io -->

2022-10-20 10:55 UTC, t184256 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @tomato42)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEokFa80Gj-4wqZViOH:-NEp0o1k3f-Jy-099-em:bhh1a9d) (no related file):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

So now we're missing integration with HandshakeSettings, sending the extension, and sending of the compressed cert if peer advertised support for compression...
</blockquote></details>

Here's a different iteration first: support for multiple compression algorithms and `xyzLoaded`-style API for feature detection. =)

___
___
*[`tlslite/messages.py` line 1296 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NEkqyHFAuzDp09YI0bf:-NEp0bKR2loZnyPf78AL:bcwxhsd) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0ade5648bfa92df5f7134d62a783cb2b1c599204/tlslite/messages.py#L1296)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

hmm, while true, I don't think we generally gain anything by importing it locally, while losing on readability, by not having all imports in one place, as is the common practice and a PEP8 recommendation...
</blockquote></details>

Now imported in a separate .utils.compression module.


<!-- Sent from Reviewable.io -->

2022-10-24 12:33 UTC, tomato42 requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 4 unresolved discussions (waiting on @t184256)

___
*[`tlslite/messages.py` line 1299 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NF8ooj1Al5ejWY2PU2M:-NF8ooj1Al5ejWY2PU2N:bgezf6c) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/22530e02435c6acc215ac28200f59022756d6bb3/tlslite/messages.py#L1299)):*
> ```Python
>         elif self.algorithm == CertificateCompressionAlgorithm.brotli:
>             if not brotliLoaded:
>                 raise ModuleNotFoundError('brotli is not available')
> ```

1. while that's the correct exception, it's the Python interpreter exception, not user code exception
It should raise tlslite-ng specific exception or a generic ValueError
2. We do need to handle this error on TLS level, but then we have sent a list of supported algorithms to the peer, so we should compare with it before trying any decompression (Certificate is the only message that actually tries to interpret the payload while parsing the message, and frankly, it's been more problematic than helpful, all the other messages and extensions just parse the values, interpretation and checking of them for consistency happens _after_ parsing)
___
*[`tlslite/messages.py` line 1328 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NF8qFUg50uY118ZmS4I:-NF8qFUg50uY118ZmS4J:b-ps1osd) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/22530e02435c6acc215ac28200f59022756d6bb3/tlslite/messages.py#L1328)):*
> ```Python
>         elif self.algorithm == CertificateCompressionAlgorithm.zstd:
>             if not zstdLoaded:
>                 raise ModuleNotFoundError('zstd is not available')
> ```

same here, wrong exception
___
*[`tlslite/utils/compression.py` line 7 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NF8qq6QEPbAO5pFvmF2:-NF8qq6QEPbAO5pFvmF3:b1js9js) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/22530e02435c6acc215ac28200f59022756d6bb3/tlslite/utils/compression.py#L7)):*
> ```Python
> 
> try:
>     import brotli
> ```

pylint waivers for unused imports may be nice here...


<!-- Sent from Reviewable.io -->

2022-11-16 15:29 UTC, tomato42 requested changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 19 unresolved discussions (waiting on @t184256)

___
*[`scripts/tls.py` line 75 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-s1G15PoyuXbBimMD:-NH-s1G15PoyuXbBimME:b8f6ezv) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L75)):*
> ```Python
>     else:
>         print("  GMPY        : Not Loaded")
>     if GMPY2_LOADED:
> ```

Maybe add lines for the compression libraries here?
___
*[`scripts/tls.py` line 116 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-sE4MDgGuEjA0lkXb:-NH-sE4MDgGuEjA0lkXc:b-ggcnpa) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L116)):*
> ```Python
>   --cert-compression - comma separated certificate compression algorithms
>                        to enable. For ex. zlib,brotli,zstd.
>                        Specify 'none' to disable.
> ```

that's not how other options work... why not have an empty string mean "disabled"?
___
*[`scripts/tls.py` line 117 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-sSek64Ad66iMQeS2:-NH-sSek64Ad66iMQeS3:b-jm32no) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L117)):*
> ```Python
>                        to enable. For ex. zlib,brotli,zstd.
>                        Specify 'none' to disable.
>                        Corresponding libraries must be available.
> ```

they must be available for the algorithm to work, not for the algorithm to be specifiable....
___
*[`scripts/tls.py` line 350 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-t9wU0d8lGRLfWa10:-NH-t9wVDymJI0X6hCLG:bvexw8h) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L350)):*
> ```Python
>         print("  Client X.509 SHA1 fingerprint: %s" % 
>             connection.session.clientCertChain.getFingerprint())
>         if connection.session.clientCertCompressionAlgorithm:
> ```

same as for server cert
___
*[`scripts/tls.py` line 362 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-stbZ1mQW3EKhtDpm:-NH-stbZ1mQW3EKhtDpn:b-9ayd7w) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L362)):*
> ```Python
>             connection.session.serverCertChain.getFingerprint())
>         if connection.session.serverCertCompressionAlgorithm:
>             print("  Server certificate compression algorithm: {0}".format(
> ```

honestly, if we're reporting the used algorithm, I'd prefer an explicit "none" if it wasn't used (to not fall into the "out of sight out for mind" trap)
___
*[`tests/tlstest.py` line 1688 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tTCh8803oGivjWS5:-NH-tTCh8803oGivjWS6:btnap1) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1688)):*
> ```Python
>             CertificateCompressionAlgorithm.zlib)
>     assert(connection.session.serverCertCompressionAlgorithm ==
>             CertificateCompressionAlgorithm.zlib)
> ```

why not simply add those asserts to the regular TLS 1.3 test with certificates?
___
*[`tests/tlstest.py` line 1787 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tiP94-nmg5Fw5XEv:-NH-tiP94-nmg5Fw5XEw:b-exgs7y) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1787)):*
> ```Python
>     assert connection.version == (3, 3)
>     assert(connection.session.clientCertCompressionAlgorithm is None)
>     assert(connection.session.serverCertCompressionAlgorithm is None)
> ```

similarly here, why not just add those asserts to a regular TLS 1.2 test with certificates?
___
*[`tests/tlstest.py` line 1802 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-u4MkBGoe48bC57Fk:-NH-u4MkBGoe48bC57Fl:b-6aarx1) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1802)):*
> ```Python
>     assert connection.version == (3, 3)
>     assert(connection.session.clientCertCompressionAlgorithm is None)
>     assert(connection.session.serverCertCompressionAlgorithm is None)
> ```

I think we can add those asserts to regular TLS 1.2 cert connections 
___
*[`tlslite/handshakesettings.py` line 191 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-ujK3690vT54C1g-c:-NH-ujK3690vT54C1g-d:bdjer5a) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L191)):*
> ```Python
> 
>         Impacts both advertized and accepted certificate compression
>         algorithms.
> ```

"affects only TLS 1.3 connections"?
___
*[`tlslite/handshakesettings.py` line 479 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wkuF4ijTtFC_A5C_:-NH-wkuF4ijTtFC_A5Ca:b250vud) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L479)):*
> ```Python
>         if unknownCertComp:
>             raise ValueError("Unknown certificate compression algorithm: {0}"\
>                              .format(unknownCertComp))
> ```

unit tests?
___
*[`tlslite/handshakesettings.py` line 718 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-v29r9pRqY-b2PfLq:-NH-v29r9pRqY-b2PfLr:bcyfrli) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L718)):*
> ```Python
>             raise ValueError("No supported ciphers")
> 
>     def _sanity_check_cert_compression(self, other):
> ```

so two methods with the same name, one just uses camelCase and the other is using underscores... that doesn't look nice to me, especially when both are called at the same time, why not have their contents in same method?
___
*[`tlslite/handshakesettings.py` line 726 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wfmH-XUEs73im2sx:-NH-wfmH-XUEs73im2sy:b250vud) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L726)):*
> ```Python
>             self._remove_all_matches(other.certCompressionAlgorithms, "brotli")
>         if not compression.zstdLoaded:
>             self._remove_all_matches(other.certCompressionAlgorithms, "zstd")
> ```

unit tests?
___
*[`tlslite/messages.py` line 1320 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH0-lKb80ta89RONDY0:-NH0-lKb80ta89RONDY1:b-2zcr4v) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/messages.py#L1320)):*
> ```Python
> 
>     def write(self):
>         if self.override_compressed_data is None:
> ```

I think it would be better to just name it "compressed_data" and have it used as the buffer for the real compressed data, so that when the message has `write()` called twice, the certificate is not compressed twice
___
*[`tlslite/messages.py` line 1329 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wWup-Gc9e4tdTmKQ:-NH-wWup-Gc9e4tdTmKR:b1co3el) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/messages.py#L1329)):*
> ```Python
>         elif self.algorithm == CertificateCompressionAlgorithm.brotli:
>             if not brotliLoaded:
>                 raise DependencyMissing('brotli is not available')
> ```

unit tests for this code?
___
*[`tlslite/messages.py` line 1333 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wcI-5OIslg0WshOO:-NH-wcI09GL8A0osJuBK:b250vud) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f [...]

2022-11-25 15:53 UTC, tomato42 requested changes
> Reviewed 1 of 1 files at r7, 7 of 7 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 9 unresolved discussions (waiting on @t184256)

___
*[`tlslite/messages.py` line 1311 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjCazBEN6thnpCveUU:-NHjCazBEN6thnpCveUV:bs6adxx) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/70aa2d91979744d6ed14f4947c8485719e2e0f0f/tlslite/messages.py#L1311)):*
> ```Python
>         elif self.algorithm == CertificateCompressionAlgorithm.brotli:
>             if not brotliLoaded:
>                 raise DependencyMissing('brotli is not available')
> ```

I don't see this exception caught in the tlsconnection code? Will it still cause the tlslite-ng to send the correct alert if client misbehaves and sends a compression type unsupported by server?
___
*[`tlslite/messages.py` line 1315 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjCrLM5d25TN0rHOds:-NHjCrLM5d25TN0rHOdt:bgposxo) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/70aa2d91979744d6ed14f4947c8485719e2e0f0f/tlslite/messages.py#L1315)):*
> ```Python
>         elif self.algorithm == CertificateCompressionAlgorithm.zstd:
>             if not zstdLoaded:
>                 raise DependencyMissing('zstd is not available')
> ```

same here as for brotli
___
*[`tlslite/messages.py` line 1319 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjCzkd126s1eEvp4d9:-NHjCzkd126s1eEvp4dA:babqcqe) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/70aa2d91979744d6ed14f4947c8485719e2e0f0f/tlslite/messages.py#L1319)):*
> ```Python
>         else:
>             raise NotImplementedError("algorithm {0} is not supported"\
>                                       .format(self.algorithm))
> ```

and here, is it caught and processed correctly?
___
*[`tlslite/tlsconnection.py` line 1298 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjTUEb3j3BTLU1gJDM:-NHjTUEb3j3BTLU1gJDN:b-rmpe2x) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/tlsconnection.py#L1298)):*
> ```Python
>         serverCertCompressionAlgorithm = None
>         if not sr_psk:
>             clientHello.getExtension(ExtensionType.key_share)
> ```

this looks out of place here...
___
*[`tlslite/tlsconnection.py` line 2942 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjTunACiSwT9X14i1r:-NHjTunACiSwT9X14i1s:bl1pd41) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/tlsconnection.py#L2942)):*
> ```Python
>                     break
>             client_certificate = result
>             assert isinstance(certificate,
> ```

shouldn't that be `client_certificate`?


<!-- Sent from Reviewable.io -->

2022-11-29 12:02 UTC, t184256 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: 12 of 16 files reviewed, 9 unresolved discussions (waiting on @staticmethod and @tomato42)

___
*[`scripts/tls.py` line 75 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-s1G15PoyuXbBimMD:-NHeYV2V3SQ05NtBrHVE:b-7tfmjp) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L75)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

Maybe add lines for the compression libraries here?
</blockquote></details>

added
___
*[`scripts/tls.py` line 116 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-sE4MDgGuEjA0lkXb:-NHeYrSk33LFcks6gZvk:b-n9tkhd) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L116)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

that's not how other options work... why not have an empty string mean "disabled"?
</blockquote></details>

changed
___
*[`scripts/tls.py` line 117 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-sSek64Ad66iMQeS2:-NHeYtez1zafnYWTlhsR:bwg0dnl) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L117)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

they must be available for the algorithm to work, not for the algorithm to be specifiable....
</blockquote></details>

reworded
___
*[`scripts/tls.py` line 350 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-t9wU0d8lGRLfWa10:-NHeYw_W1tq1lSb8FRuT:b-mmbawj) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L350)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same as for server cert
</blockquote></details>

changed to print explicit "none"
___
*[`scripts/tls.py` line 362 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-stbZ1mQW3EKhtDpm:-NHeZ4IN62dp7IG4CLEH:b-mmbawj) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/scripts/tls.py#L362)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

honestly, if we're reporting the used algorithm, I'd prefer an explicit "none" if it wasn't used (to not fall into the "out of sight out for mind" trap)
</blockquote></details>

changed to print explicit "none"
___
*[`tests/tlstest.py` line 1688 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tTCh8803oGivjWS5:-NHeZ5Pd8jGGyX_6jUWj:b-i9n389) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1688)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why not simply add those asserts to the regular TLS 1.3 test with certificates?
</blockquote></details>

I couldn't single out one ultimate regular TLS 1.3 test, which one do you have in mind? Or have you meant all of them?
___
*[`tests/tlstest.py` line 1787 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tiP94-nmg5Fw5XEv:-NHe_9aL0JZytvmLB1BW:b3hly4r) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1787)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

similarly here, why not just add those asserts to a regular TLS 1.2 test with certificates?
</blockquote></details>

This one is slightly different in that I explicitly specify three algorithms as allowed.
___
*[`tests/tlstest.py` line 1802 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-u4MkBGoe48bC57Fk:-NHe_H6X92nirdVd3dRk:b-vwxu4x) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1802)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I think we can add those asserts to regular TLS 1.2 cert connections 
</blockquote></details>

Which ones? All of them?
___
*[`tlslite/handshakesettings.py` line 191 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-ujK3690vT54C1g-c:-NHe_RqTDZ7QzyCJi-cm:bqmjwcz) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L191)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

"affects only TLS 1.3 connections"?
</blockquote></details>

Added.
___
*[`tlslite/handshakesettings.py` line 479 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wkuF4ijTtFC_A5C_:-NHe_Uo26YvKQmMIdyiI:bomabml) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L479)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

unit tests?
</blockquote></details>

added (`test_certCompressionAlgorithms*`)
___
*[`tlslite/handshakesettings.py` line 718 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-v29r9pRqY-b2PfLq:-NHeaRxC5G_r-vEtvfHR:b-ses316) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L718)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

so two methods with the same name, one just uses camelCase and the other is using underscores... that doesn't look nice to me, especially when both are called at the same time, why not have their contents in same method?
</blockquote></details>

This is consistent with, say, @staticmethod `_sanityCheckCipherSettings`erroring out on unknown names and non-@staticmethod `_sanity_check_ciphers` filtering out unsupported ones. Should I merge these too? 
___
*[`tlslite/handshakesettings.py` line 726 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wfmH-XUEs73im2sx:-NHeaMz16tPJE7x0sss-:brhx7dl) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L726)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

unit tests?
</blockquote></details>

added (`test_certCompressionAlgorithms_filtering_out`)
___
*[`tlslite/messages.py` line 1320 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH0-lKb80ta89RONDY0:-NHebXZPAWzyqgmLI2Dj:b-1jucj9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/messages.py#L1320)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I think it would be better to just name it "compressed_data" and have it used as the buffer for the real compressed data, so that when the message has `write()` called twice, the certificate is not compressed twice
</blockquote></details>

Renamed. With a megaton of asserts plastered around the methods, there's now a high-level interface that performs compression on `create` or setting `cert_chain`, and a low-level interface to override `compressed_certificate_message` and `uncompressed_length`.
___
*[`tlslite/messages.py` line 1329 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wWup-Gc9e4tdTmKQ:-NHecli38eQxj79QtY9p:b-ggtnce) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/messages.py#L1329)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

unit tests for this code?
</blockquote></details>

added (`test_unavailable_argorithms`)
___
*[`tlslite/messages.py` line 1333 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-wcI-5OIslg0WshOO:-NHecMYK3FxsAXQHP52t:b-ggtnce) ([raw file](https://github.com/tlsfuzzer/tlslite-n [...]

2022-11-29 12:35 UTC, t184256 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: 12 of 16 files reviewed, 9 unresolved discussions (waiting on @staticmethod and @tomato42)

___
*[`tlslite/messages.py` line 1311 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjCazBEN6thnpCveUU:-NI2MsVgCclBN1NEJrls:bye2hpc) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/70aa2d91979744d6ed14f4947c8485719e2e0f0f/tlslite/messages.py#L1311)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I don't see this exception caught in the tlsconnection code? Will it still cause the tlslite-ng to send the correct alert if client misbehaves and sends a compression type unsupported by server?
</blockquote></details>

Changed to BadCertificate (in parsing only)
___
*[`tlslite/messages.py` line 1315 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjCrLM5d25TN0rHOds:-NI2NceG5531RsxuYDHq:bye2hpc) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/70aa2d91979744d6ed14f4947c8485719e2e0f0f/tlslite/messages.py#L1315)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here as for brotli
</blockquote></details>

Changed to BadCertificate (in parsing only)
___
*[`tlslite/messages.py` line 1319 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NHjCzkd126s1eEvp4d9:-NI2NdR-ERKgcch4r2Ir:bye2hpc) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/70aa2d91979744d6ed14f4947c8485719e2e0f0f/tlslite/messages.py#L1319)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

and here, is it caught and processed correctly?
</blockquote></details>

Changed to BadCertificate (in parsing only)


<!-- Sent from Reviewable.io -->

2022-11-29 13:24 UTC, tomato42 requested changes
> Reviewed 2 of 4 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 3 unresolved discussions (waiting on @staticmethod and @t184256)

___
*[`tests/tlstest.py` line 1688 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tTCh8803oGivjWS5:-NI2XfQH0dUTsfSVIKf1:b-kn9v5y) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1688)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

I couldn't single out one ultimate regular TLS 1.3 test, which one do you have in mind? Or have you meant all of them?
</blockquote></details>

just one, "good mutual X.509"
___
*[`tests/tlstest.py` line 1787 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tiP94-nmg5Fw5XEv:-NI2Xmj11RdJHjvQlY_p:bkncd4i) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1787)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

This one is slightly different in that I explicitly specify three algorithms as allowed.
</blockquote></details>

ok, then we can keep it
___
*[`tests/tlstest.py` line 1802 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-u4MkBGoe48bC57Fk:-NI2XsNr3HdUZiet88vJ:btvopiu) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1802)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

Which ones? All of them?
</blockquote></details>

just one is enough, like "good mutual Ed25519 X.509, TLS 1.2"


<!-- Sent from Reviewable.io -->

2022-11-29 13:27 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 3 unresolved discussions (waiting on @staticmethod and @t184256)

___
*[`tlslite/handshakesettings.py` line 718 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-v29r9pRqY-b2PfLq:-NI2Z69x2O9XayKiYPIQ:b2956e9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L718)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

This is consistent with, say, @staticmethod `_sanityCheckCipherSettings`erroring out on unknown names and non-@staticmethod `_sanity_check_ciphers` filtering out unsupported ones. Should I merge these too? 
</blockquote></details>

if you want to... yes, but that feels like something that belongs to a separate PR


<!-- Sent from Reviewable.io -->

2022-11-29 17:00 UTC, t184256 reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @staticmethod and @tomato42)

___
*[`tests/tlstest.py` line 1688 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-tTCh8803oGivjWS5:-NI3HxNK0sacZiKiR-Sk:ba1uwtq) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1688)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

just one, "good mutual X.509"
</blockquote></details>

OK, moved into "good mutual X.509, TLS v1.3"
___
*[`tests/tlstest.py` line 1802 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-u4MkBGoe48bC57Fk:-NI3ItUm3iiTcQ3WDw_q:b-otz936) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tests/tlstest.py#L1802)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

just one is enough, like "good mutual Ed25519 X.509, TLS 1.2"
</blockquote></details>

Added to "good mutual Ed25519 X.509, TLS 1.2"
___
*[`tlslite/handshakesettings.py` line 718 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-v29r9pRqY-b2PfLq:-NI3J2yt6o0ia8DYuTGR:bwfqp0r) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L718)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

if you want to... yes, but that feels like something that belongs to a separate PR
</blockquote></details>

let's proliferate the pattern for now


<!-- Sent from Reviewable.io -->

2022-11-30 14:03 UTC, tomato42 requested changes
overall looks good, but the `test_read_mock_unavailable (unit_tests.test_tlslite_messages.TestCompressedCertificate)` needs a fix so it passes in all environments (the exception should be caught with a `assertRaises`

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-:-NI7q3eu0TtOPPMNJ_93:bwowokn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @t184256)

___
*[`tlslite/handshakesettings.py` line 718 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NH-v29r9pRqY-b2PfLq:-NI7pkwt0ch_beM6yKWu:b32wtd) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/38b8384e4d685fee8a1494399b86cb4f952648f5/tlslite/handshakesettings.py#L718)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

let's proliferate the pattern for now
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-11-30 14:07 UTC, tomato42 commented
also, while the complexity and duplication notifications from CodeClimate are more false positives, the nits around formatting are valid

2022-11-30 15:14 UTC, tomato42 approved these changes
r+

> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-:-NI85_gl-XrolF9tu4Hk:b32wu6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @t184256)



<!-- Sent from Reviewable.io -->

2022-12-06 18:41 UTC, tomato42 requested changes
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 4 unresolved discussions (waiting on @t184256)

___
*[`tlslite/tlsconnection.py` line 1326 at r13](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIciULcDEm4U6k-2Lve:-NIciULcDEm4U6k-2Lvf:b-2vrhbo) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/9fa51bbfdd905fcef0138394b9abb2af1358fbaf/tlslite/tlsconnection.py#L1326)):*
> ```Python
>                               (Certificate, CompressedCertificate))
>             if isinstance(certificate, CompressedCertificate):
>                 serverCertCompressionAlgorithm = certificate.algorithm
> ```

we should verify here that it's one of the algorithms advertised in Client Hello
___
*[`tlslite/tlsconnection.py` line 1690 at r13](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIcj7KH2Vn62U6RYKDT:-NIcj7KH2Vn62U6RYKDU:b-wlvzcm) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/9fa51bbfdd905fcef0138394b9abb2af1358fbaf/tlslite/tlsconnection.py#L1690)):*
> ```Python
>             for result in self._getMsg(ContentType.handshake,
>                                        (HandshakeType.certificate,
>                                         HandshakeType.compressed_certificate,),
> ```

it should be accepted only when the extension was sent
___
*[`tlslite/tlsconnection.py` line 2935 at r13](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIcjQtfA-mGqRpa8XuS:-NIcjQtfA-mGqRpa8XuT:b-g5bz9p) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/9fa51bbfdd905fcef0138394b9abb2af1358fbaf/tlslite/tlsconnection.py#L2935)):*
> ```Python
>             for result in self._getMsg(ContentType.handshake,
>                                        (HandshakeType.certificate,
>                                         HandshakeType.compressed_certificate,),
> ```

should be accepted only when extension was exchanged
___
*[`tlslite/tlsconnection.py` line 2946 at r13](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIcjUffDunA2yg9-HuT:-NIcjUffDunA2yg9-HuU:b4fxbvj) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/9fa51bbfdd905fcef0138394b9abb2af1358fbaf/tlslite/tlsconnection.py#L2946)):*
> ```Python
>             client_cert_chain = client_certificate.cert_chain
>             if isinstance(client_certificate, CompressedCertificate):
>                 clientCertCompressionAlgorithm = client_certificate.algorithm
> ```

we should verify that the algorithm is one of the advertised ones in the extension


<!-- Sent from Reviewable.io -->

2022-12-08 12:06 UTC, tomato42 requested changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484)* status: all files reviewed, 5 unresolved discussions (waiting on @t184256)

___
*[`tlslite/extensions.py` line 507 at r14](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIlZTu14VUQUgW41j-D:-NIlZTu14VUQUgW41j-E:b-hicovo) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/3bc9f37b0f2907983db6116daadaa8bb47c5c6d0/tlslite/extensions.py#L507)):*
> ```Python
>         if self._ceiling is not None and l > self._ceiling:
>             raise DecodeError("Extension payload too long "
>                               "(>{0})".format(self._ceiling))
> ```

no, that's not how we implement this, it should be done by checking sanity of the extension, that the extracted list is not empty. The ceiling limit is implicit as the specified length of encoded length is one byte, and items are two bytes long.
___
*[`tlslite/tlsconnection.py` line 1334 at r14](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIl_5P74kTPB2YQYo0h:-NIl_5P74kTPB2YQYo0i:b-s695j1) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/3bc9f37b0f2907983db6116daadaa8bb47c5c6d0/tlslite/tlsconnection.py#L1334)):*
> ```Python
>                 if not comp_ext:
>                     for result in self._sendError(
>                             AlertDescription.unexpected_message,
> ```

this will never be reached, the _getMsg won't accept a compressed certificate if it's not in the allowed handshake_types
___
*[`tlslite/tlsconnection.py` line 1708 at r14](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIlbSHT11nBPjwkVwk5:-NIlbSHT11nBPjwkVwk6:b4tslu9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/3bc9f37b0f2907983db6116daadaa8bb47c5c6d0/tlslite/tlsconnection.py#L1708)):*
> ```Python
>             handshake_types = (HandshakeType.certificate,)
>             if ch_cert_comp_ext:
>                 handshake_types += (HandshakeType.compressed_certificate,)
> ```

actually, this shouldn't be here at all: `_clientKeyExchange` is TLS 1.2 and earlier only, while compresssed_certificate is for TLS 1.3 only, it should be in `_clientTLS13Handshake` only
___
*[`tlslite/tlsconnection.py` line 2973 at r14](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/484#-NIl_ils5viZvYRHVXTz:-NIl_ils5viZvYRHVXU-:b-x8f7g3) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/3bc9f37b0f2907983db6116daadaa8bb47c5c6d0/tlslite/tlsconnection.py#L2973)):*
> ```Python
>                 if not comp_ext:
>                     for result in self._sendError(
>                             AlertDescription.unexpected_message,
> ```

same here, this code will never be reached


<!-- Sent from Reviewable.io -->

2024-07-24 15:27 UTC, GeorgePantelakis commented
Obsoleted by: #521

2024-07-24 15:28 UTC, closed without merging