Add support for compress_certificate extension
tlsfuzzer/tlslite-ng pull request #491
Opened 2023-05-23 11:29 UTC by charxhit

This implements Certificate Compression extension and msg (rfc 8879). Unfortunately, I saw that there was already an open pull request #484 addressing the same a little too late. To avoid repetition, I skimmed through the discussion and implemented relevant feedback. The two main differences in the implementation of the above pull request and this one is that:

1. We keep class `Certificate` and class `CompressedCertificate` separate (instead of the latter being a wrapper around the first)
2. We handle validation checks in the calling code, not during message parsing

This keeps integration with tlslite-ng relatively simple. To help with the review, here's what the pull request is meant to add:

- Support for sending `compress_certificate` extension as a client
- Support for parsing `CompressedCertificate` msg as a client
- Support for parsing `compress_certificate` extension in `CertificateRequest` msg
- Ability to send a `CompressedCertificate` msg if the server advertises support for compression

The server equivalent of the above points are not present yet but can be trivially added after initial review.  One area that needs attention is the code for `CompressedCertificate` class, specifically the `.create()` and `decompress()` methods (I have added relevant comments explaining the problem). The rfc was a bit vague to me on what exact bytes the encoded compressed certificate msg will have (whether it's type + length + encoded message after decompression or just length + encoded msg), so some changes might be needed there but they should be minimal. For this reason, I have not added tests for `CompressedCertificate` msg

2023-05-23 15:21 UTC, tomato42 requested changes
> We keep class Certificate and class CompressedCertificate separate (instead of the latter being a wrapper around the first)

this will make it not transparent and complicate the rest of the code

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 5 of 5 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-:-NW85Yq0645gsrTHqrL1:b-52q9s9)* status: all files reviewed, 21 unresolved discussions (waiting on @charxhit)

___
*[`-- commits` line 23 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89ZGfBjWtg-1WKFWR):*
fixup commit, so should be squashed
___
*[`tlslite/constants.py` line 192 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW84ade-ZWDnz8N8HWd:-NW84ade-ZWDnz8N8HWe:bv4wk3s) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/792644d3a18fce993dcf5adbbecd1e53ce6e59f7/tlslite/constants.py#L192)):*
> ```Python
>     zstd = 3
>     all = (1, 2, 3)
>     default = (1,)
> ```

we generally don't create such values and they will interact badly with enum handling code of extensions



_Code quote:_
```Python
    all = (1, 2, 3)
    default = (1,)
```
___
*[`tlslite/extensions.py` line 2103 at r3](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW86Mba2W8k2OBiewdH:-NW86Mba2W8k2OBiewdI:b9lykil) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f5a0df0c3b90102029c6887e02bb013f4ac9cd32/tlslite/extensions.py#L2103)):*
> ```Python
> 
> 
> class CompressCertificateExtension(TLSExtension):
> ```

why it's not a `VarListExtension` ?
___
*[`tlslite/extensions.py` line 2124 at r3](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW85o6xClg_ltgAaJOz:-NW85o6xClg_ltgAaJP-:b-uxl7ic) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f5a0df0c3b90102029c6887e02bb013f4ac9cd32/tlslite/extensions.py#L2124)):*
> ```Python
> 
>         if not all([algo in CompressionAlgorithms.all for algo in self.advertised_algorithms]):
>             raise TLSInternalError("Unknown algorithm provided for certificate compression")
> ```

for tlsfuzzer we generally want the ability to send unassigned values, making sure that the user can't set invalid values should happen like 2 API levels higher (in HandshakeSettings)
___
*[`tlslite/extensions.py` line 2148 at r3](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW86_jl9TBI1BKlWdE6:-NW86_jl9TBI1BKlWdE7:bi5l9w9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f5a0df0c3b90102029c6887e02bb013f4ac9cd32/tlslite/extensions.py#L2148)):*
> ```Python
> 
> 
> TLSExtension._universalExtensions = \
> ```

why `CompressCertificateExtension` is not added here?
___
*[`tlslite/extensions.py` line 2116 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89v7Z3qx9qCaADArw:-NW89v7_9CHSjaZCNdFf:b-2opgyz) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/4beec07870b3fcef5158d4fd8a7f7ec8f644892e/tlslite/extensions.py#L2116)):*
> ```Python
>             advertised_algorithms: an iterable of integers denoting which algorithms the peer
>                                    supports for compression
>         """
> ```

that's not correct Sphinx syntax for param docs
___
*[`tlslite/extensions.py` line 2120 at r9](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8Atca-Mjfw-HLxFOq:-NW8Atca-Mjfw-HLxFOr:b-qo3pkb) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0018d545b3409eedf04e3abd1e4ce9ad4f4e025a/tlslite/extensions.py#L2120)):*
> ```Python
>         # generic code allows empty, this ext does not
>         if not parser.getRemainingLength():
>             raise DecodeError("Empty payload in extension")
> ```

That's not what I see in the VarListExtension...
___
*[`tlslite/extensions.py` line 2130 at r9](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8B2bHBqHiKUzj7ULo:-NW8B2bHBqHiKUzj7ULp:b-bs9u0n) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0018d545b3409eedf04e3abd1e4ce9ad4f4e025a/tlslite/extensions.py#L2130)):*
> ```Python
>                                    supports for compression
>         """
>         return super(CompressCertificateExtension, self).create(advertised_algorithms)
> ```

why have it in the first place then?
___
*[`tlslite/handshakesettings.py` line 384 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW87DGv1YBZwgK6oYFB:-NW87DGv1YBZwgK6oYFC:b-z6khjb) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f0381d80def52c9d31e66ba9acd663f6e0af84cb/tlslite/handshakesettings.py#L384)):*
> ```Python
>         # certificate compression extensions
>         self.use_certificate_compression = False
>         self.certificate_compression_algorithms = CompressionAlgorithms.default
> ```

why split use and list of allowed? why an empty list can't mean "don't use"?
___
*[`tlslite/handshakesettings.py` line 616 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW875VR0X0PvyHZ5h-W:-NW875VR0X0PvyHZ5h-X:b-yc3di7) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f0381d80def52c9d31e66ba9acd663f6e0af84cb/tlslite/handshakesettings.py#L616)):*
> ```Python
> 
>         if other.use_certificate_compression not in (True, False):
>             raise ValueError("use_heartbeat_extension must be True or False")
> ```

it's no heartbeat
___
*[`tlslite/handshakesettings.py` line 628 at r10](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8BAn25qUOJXA-Lbvk:-NW8BAn25qUOJXA-Lbvl:b-olse8h) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/ad1ac48eb2b4f25c4e24eea4c9e995cdad70cd84/tlslite/handshakesettings.py#L628)):*
> ```Python
> 
>         if other.use_certificate_compression not in (True, False):
>             raise ValueError("use_certificate_compression must be True or False")
> ```

squash fixup commits, don't add them
___
*[`tlslite/messages.py` line 24 at r5](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW87Rfe2q0sZbyuyU2b:-NW87RffA1kcgMcspCKA:bndk6c8) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/56d5880754dde0f8c48d3b129d9d5461ebb39e55/tlslite/messages.py#L24)):*
> ```Python
> from .extensions import *
> from .utils.format_output import none_as_unknown
> from utils import compression
> ```

use relative imports
___
*[`tlslite/messages.py` line 24 at r7](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89O48A06X026n7YNe:-NW89O49CI93rZC3QVVl:b2gwkek) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/100c3478872dbaddab052893f0f70d002b8d106a/tlslite/messages.py#L24)):*
> ```Python
> from .extensions import *
> from .utils.format_output import none_as_unknown
> from .utils import compression
> ```

fixup commits need to be squashed as CI verifies that the tests pass after every commit
___
*[`tlslite/messages.py` line 1375 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8AOYuAJ_9Ob9G3Ua4:-NW8AOYuAJ_9Ob9G3Ua5:bj94545) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/4beec07870b3fcef5158d4fd8a7f7ec8f644892e/tlslite/messages.py#L1375)):*
> ```Python
>         Args:
>             chosen_algorithm - An int denoting an algorithm to be used to create the compressed msg
>             certificate_message - Object of class messages.Certificate whose data will be encoded
> ```

not valid Sphinx syntax
___
*[`tlslite/tlsconnection.py` line 1281 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW88CQFBgwaf9PBQBIr:-NW88CQFBgwaf9PBQBIs:bb58xkz) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/7884b15260a441bbc4daaf3db8e2b3c963fb399f/tlslite/tlsconnection.py#L1281)):*
> ```Python
>         certificate_request = None
>         certificate = None
>         compress_cert_ext = clientHello.getExtension(ExtensionType.compress_certificate)
> ```

no? The extension is negotiated when the _server_ sends the extension, not when the client advertised support for it
___
*[`tlslite/tlsconnection.py` line 1469 at r6](h [...]

2023-05-24 07:59 UTC, charxhit reviewed
Clarification: CompressedCertificate still depends on Certificate class to make sense of the compressed message, but unlike in the previous pull request, it doesn't attempt to act as a proxy to it. Can you give an example of a possible complication here so I understand what you are referring to?

> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-:-NWBjlAe7CnawcRsDqnZ:bf4jtfb)* status: 3 of 9 files reviewed, 21 unresolved discussions (waiting on @tomato42)

___
*[`-- commits` line 23 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89ZGfBjWtg-1WKFWR):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

fixup commit, so should be squashed
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/constants.py` line 192 at r2](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW84ade-ZWDnz8N8HWd:-NWBehRH0kZoAtZW6Gen:b-logmj3) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/792644d3a18fce993dcf5adbbecd1e53ce6e59f7/tlslite/constants.py#L192)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

we generally don't create such values and they will interact badly with enum handling code of extensions
</blockquote></details>

Removed from enum class and added to `utils.compression`
___
*[`tlslite/extensions.py` line 2103 at r3](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW86Mba2W8k2OBiewdH:-NWBeoBA3NOK-NM5o8ji:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f5a0df0c3b90102029c6887e02bb013f4ac9cd32/tlslite/extensions.py#L2103)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why it's not a `VarListExtension` ?
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/extensions.py` line 2124 at r3](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW85o6xClg_ltgAaJOz:-NWBfmma-ptdwV3CEoVK:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f5a0df0c3b90102029c6887e02bb013f4ac9cd32/tlslite/extensions.py#L2124)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

for tlsfuzzer we generally want the ability to send unassigned values, making sure that the user can't set invalid values should happen like 2 API levels higher (in HandshakeSettings)
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/extensions.py` line 2148 at r3](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW86_jl9TBI1BKlWdE6:-NWBgJbL8m20GmUp35X5:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f5a0df0c3b90102029c6887e02bb013f4ac9cd32/tlslite/extensions.py#L2148)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why `CompressCertificateExtension` is not added here?
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/extensions.py` line 2116 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89v7Z3qx9qCaADArw:-NWBflAD6ZP44prvHUbb:b-886gsx) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/4beec07870b3fcef5158d4fd8a7f7ec8f644892e/tlslite/extensions.py#L2116)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

that's not correct Sphinx syntax for param docs
</blockquote></details>

Fixed
___
*[`tlslite/extensions.py` line 2120 at r9](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8Atca-Mjfw-HLxFOq:-NWBepvZ0MDFFDTxkfSi:bhak47q) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0018d545b3409eedf04e3abd1e4ce9ad4f4e025a/tlslite/extensions.py#L2120)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

That's not what I see in the VarListExtension...
</blockquote></details>

Do you mean that VarListExtension rejects empty extension data fields as well when parsing? When I reviewed the parse() method it seemed to just set the `internal_value` as `None` in case of no extension payload...
___
*[`tlslite/extensions.py` line 2130 at r9](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8B2bHBqHiKUzj7ULo:-NWBfndJAbYv7DkqoeDQ:bx35hpe) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0018d545b3409eedf04e3abd1e4ce9ad4f4e025a/tlslite/extensions.py#L2130)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why have it in the first place then?
</blockquote></details>

So that IDE s and debugging tools can point to a relevant docstring which would make more sense than the super() function's one to someone going through the code. Do you prefer the code without this wrapper? 
___
*[`tlslite/handshakesettings.py` line 384 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW87DGv1YBZwgK6oYFB:-NWBgLLw8dCXQXz9oLp8:b-ux659y) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f0381d80def52c9d31e66ba9acd663f6e0af84cb/tlslite/handshakesettings.py#L384)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why split use and list of allowed? why an empty list can't mean "don't use"?
</blockquote></details>

I wrote it like this to be more explicit and readable + provide a safe default for users that just want to enable certificate compression without knowing about the algorithms used. I can change the code to only accept one flag if you prefer it that way.
___
*[`tlslite/handshakesettings.py` line 616 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW875VR0X0PvyHZ5h-W:-NWBhD3hB451ySJU0U5j:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f0381d80def52c9d31e66ba9acd663f6e0af84cb/tlslite/handshakesettings.py#L616)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

it's no heartbeat
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/handshakesettings.py` line 628 at r10](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8BAn25qUOJXA-Lbvk:-NWBhDpB0pROIcIStrEt:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/ad1ac48eb2b4f25c4e24eea4c9e995cdad70cd84/tlslite/handshakesettings.py#L628)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

squash fixup commits, don't add them
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/messages.py` line 24 at r5](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW87Rfe2q0sZbyuyU2b:-NWBhF4T3ylt9FquAQg8:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/56d5880754dde0f8c48d3b129d9d5461ebb39e55/tlslite/messages.py#L24)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

use relative imports
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/messages.py` line 24 at r7](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89O48A06X026n7YNe:-NWBhFiq60Pw4x-t2LsG:b-4a1f7e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/100c3478872dbaddab052893f0f70d002b8d106a/tlslite/messages.py#L24)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

fixup commits need to be squashed as CI verifies that the tests pass after every commit
</blockquote></details>

Fixed in a now squashed commit
___
*[`tlslite/messages.py` line 1375 at r8](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8AOYuAJ_9Ob9G3Ua4:-NWBhGcpECfGgOiXdBE8:b-886gsx) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/4beec07870b3fcef5158d4fd8a7f7ec8f644892e/tlslite/messages.py#L1375)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

not valid Sphinx syntax
</blockquote></details>

Fixed
___
*[`tlslite/tlsconnection.py` line 1281 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW88CQFBgwaf9PBQBIr:-NWBhJqZ5mfahBm0FcYu:bec2c5m) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/7884b15260a441bbc4daaf3db8e2b3c963fb399f/tlslite/tlscon [...]

2023-05-24 08:01 UTC, charxhit commented
Commits should be fixed from now on

2023-05-31 13:44 UTC, tomato42 requested changes
that other PR is related to this one: https://github.com/tlsfuzzer/tlsfuzzer/pull/802

and just as a head's up: for it to be mergable both client and server side support needs to be implemented

(and sorry for the slow review, I was busy with urgent stuff at work)

> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-:-NWlZ-5u34sIdsci3pCg:bp1vpkz)* status: all files reviewed, 3 unresolved discussions (waiting on @charxhit)

___
*[`-- commits` line 2 at r12](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NWlZ6HwAdSLpmOoIEA_):*
the commit message should still describe what's being done
___
*[`tlslite/extensions.py` line 2120 at r9](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8Atca-Mjfw-HLxFOq:-NWlcwnUEwslbIZLYgqG:b-wtw245) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0018d545b3409eedf04e3abd1e4ce9ad4f4e025a/tlslite/extensions.py#L2120)):*
<details><summary><i>Previously, charxhit wrote…</i></summary><blockquote>

Do you mean that VarListExtension rejects empty extension data fields as well when parsing? When I reviewed the parse() method it seemed to just set the `internal_value` as `None` in case of no extension payload...
</blockquote></details>

aah, right, it's about the whole extension being empty, not extra data
___
*[`tlslite/extensions.py` line 2130 at r9](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW8B2bHBqHiKUzj7ULo:-NWlsFsj8C-AyOIDYvF7:b40fpef) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/0018d545b3409eedf04e3abd1e4ce9ad4f4e025a/tlslite/extensions.py#L2130)):*
<details><summary><i>Previously, charxhit wrote…</i></summary><blockquote>

So that IDE s and debugging tools can point to a relevant docstring which would make more sense than the super() function's one to someone going through the code. Do you prefer the code without this wrapper? 
</blockquote></details>

I haven't been making them, and I didn't feel like they were missing, but despite the verbosity it's probably fine to have class specific doc text.
___
*[`tlslite/handshakesettings.py` line 384 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW87DGv1YBZwgK6oYFB:-NWlsfNp1VgnUnuoE9KA:b-buyle1) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/f0381d80def52c9d31e66ba9acd663f6e0af84cb/tlslite/handshakesettings.py#L384)):*
<details><summary><i>Previously, charxhit wrote…</i></summary><blockquote>

I wrote it like this to be more explicit and readable + provide a safe default for users that just want to enable certificate compression without knowing about the algorithms used. I can change the code to only accept one flag if you prefer it that way.
</blockquote></details>

but then, why disable it by default?
___
*[`tlslite/tlsconnection.py` line 1281 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW88CQFBgwaf9PBQBIr:-NWltO7c9u_knGxeyByg:b-4pv997) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/7884b15260a441bbc4daaf3db8e2b3c963fb399f/tlslite/tlsconnection.py#L1281)):*
<details><summary><i>Previously, charxhit wrote…</i></summary><blockquote>

That does not seem to be the case with certificate_extension. Relevant quotes from the rfc:
 
1. "_Whenever [client_certificate] is sent by the client as a ClientHello message extension...it indicates support for compressed server certificates. Whenever it is sent by the server as a CertificateRequest extension...it indicates support for compressed client certificates_"

2. "_The compress_certificate extension is a unidirectional indication; no corresponding response extension is needed_"

rfc suggests that unlike other extensions, formal negotiation for this extension is not required and the valid places for it include only the ClientHello and CertificateRequest
</blockquote></details>

aah, right, I was misremembering the RFC
___
*[`tlslite/tlsconnection.py` line 1475 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/491#-NW89EI3-jjvyU5dzLgM:-NWltpoY13QpKvl4f0jR:b-9ddjkv) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/7884b15260a441bbc4daaf3db8e2b3c963fb399f/tlslite/tlsconnection.py#L1475)):*
<details><summary><i>Previously, charxhit wrote…</i></summary><blockquote>

see above, it seems that they will remain relevant throughout the handshake because we will check the server's algorithm in CertificateRequest against the ones we advertised in ClientHello (again, a compress_certificate extension in ServerHello is not expected)
</blockquote></details>

based on what? Server doesn't have to limit extensions sent in CR to the ones advertised by client
and while we should use only algorithms we support, that should be based on HandshakeSettings, not
values in the extension.


<!-- Sent from Reviewable.io -->

2024-07-24 15:28 UTC, GeorgePantelakis commented
Obsoleted by: #521

2024-07-24 15:28 UTC, closed without merging