Support for compressed certificate
tlsfuzzer/tlslite-ng pull request #521
Opened 2024-06-19 17:37 UTC by GeorgePantelakis

Added support in client and server for the TLS Certificate Compression as described in https://www.rfc-editor.org/rfc/rfc8879.html

2024-06-20 11:07 UTC, tomato42 requested changes
The CI will need to be extended with a combination of the packages that implement the zstd and brotli compression...

> Reviewed 10 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-:-O-pK3a87tSZi0ldd_6A:bhcfr7n)* status: 8 of 23 files reviewed, 32 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-p9CiH3fwnTIf4I0da):*
"Support for compressed_certificate extension"?
___
*[`scripts/tls.py` line 81 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pIvN25KtdzfNaYJg2:-O-pIvN25KtdzfNaYJg3:b-65muar) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/scripts/tls.py#L81)):*
> ```Python
> 
>     print("")
>     print("Compression:")
> ```

"Certificate Compression"?
___
*[`tests/tlstest.py` line 2041 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pJghl-oManbtGfq6f:-O-pJghl-oManbtGfq6g:b17aek0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tests/tlstest.py#L2041)):*
> ```Python
>     assert connection.extendedMasterSecret
>     assert connection.session.appProto is None
>     assert connection.server_cert_compression_algo == "zlib"
> ```

since client cert was not used here, we should also assert that the client side is None
and also add it to the client side of this test

similarly, we should add this assert to one of the tests that do use client certificates, to show that it is set for client certificates too
___
*[`tests/tlstest.py` line 2082 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pJZJC01BL070Jnlon:-O-pJZJC01BL070Jnloo:b5sho4h) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tests/tlstest.py#L2082)):*
> ```Python
>     settings.certificate_compression_send = []
>     connection = connect()
>     connection.handshakeClientCert(serverName=address[0],
> ```

this should be HandshakeServer...
___
*[`tlslite/constants.py` line 585 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pB-ndBpT_Pgwv3Vcs:-O-pB-ndBpT_Pgwv3Vct:bexfc80) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/constants.py#L585)):*
> ```Python
>     psk_dhe_ke = 1
> 
> class CompressionAlgorithm(TLSEnum):
> ```

In the RFC it's a `CertificateCompressionAlgorithm`...
___
*[`tlslite/constants.py` line 586 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pB2kmEFyP-KkLgC87:-O-pB2kmEFyP-KkLgC88:b-5dovps) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/constants.py#L586)):*
> ```Python
> 
> class CompressionAlgorithm(TLSEnum):
>     """Compression algorithms used for the compression of certificates."""
> ```

please add reference to the RFC here
___
*[`tlslite/constants.py` line 591 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pAhno8AfAWiVIgLve:-O-pAhno8AfAWiVIgLvf:b-gtoqk0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/constants.py#L591)):*
> ```Python
>     brotli = 2
>     zstd = 3
>     all = [1, 2, 3]
> ```

if you define `all` then you need to also re-declare `def toRepr` that that ignores it, see `ECPointFormat`
___
*[`tlslite/extensions.py` line 2161 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pBaBFCPhXKGVQV51h:-O-pBaBFCPhXKGVQV51i:b-wncls2) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/extensions.py#L2161)):*
> ```Python
> 
> 
> class CompressCertificateExtension(VarListExtension):
> ```

I don't think we need to shorten it, I think it can be the full `CertificateCompressionAlgorithmsExtension` (from struct name) or `CompressedCertificateExtension` (from the extension ID name)
___
*[`tlslite/handshakesettings.py` line 372 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pCDeS3DvR_ytzCXnU:-O-pCDeS3DvR_ytzCXnV:b-v8mlvi) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L372)):*
> ```Python
> 
>     :vartype certificate_compression_send: list(str)
>     :ivar certificate_compression: a list of compression algorithms that will
> ```

should be `:ivar certificate_compression_send:`
___
*[`tlslite/handshakesettings.py` line 378 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pCIsB96hynlHA8-BX:-O-pCIsB96hynlHA8-BY:bxxr3p) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L378)):*
> ```Python
> 
>     :vartype certificate_compression_receive: list(str)
>     :ivar certificate_compression: a list of compression algorithms that will
> ```

should be `:ivar certificate_compression_receive:`
___
*[`tlslite/handshakesettings.py` line 640 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pCq1VEnk3T425uecT:-O-pCq1VEnk3T425uecU:b-4i90v5) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L640)):*
> ```Python
> 
>         if other.certificate_compression_send:
>             if isinstance(other.certificate_compression_send, str):
> ```

err... I don't think we want to support string as the value, if the user wants to use a specific algorithm, they can set it to a tuple
___
*[`tlslite/handshakesettings.py` line 644 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pD6z8EBZoKtVpfOKG:-O-pD6z8EBZoKtVpfOKH:b-6sqii0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L644)):*
> ```Python
>                     other.certificate_compression_send
>                 ]
>             elif not isinstance(other.certificate_compression_send, list):
> ```

a `tuple` should also be accepted... :grin: 
in general we just need an iterable, as long as we can iterate over it, we're good, there's no need to do an explicit check for the tape
___
*[`tlslite/handshakesettings.py` line 659 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pDeGi-sgQnW2KfBLs:-O-pDeGi-sgQnW2KfBLt:b4df3qv) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L659)):*
> ```Python
>                     other.certificate_compression_receive
>                 ]
>             elif not isinstance(other.certificate_compression_receive, list):
> ```

same here, no need for explicit check
___
*[`tlslite/messages.py` line 556 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pDvT_5TNI4jHGK6Ft:-O-pDvTaDD0PXGt_bmm_:bej2596) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/messages.py#L556)):*
> ```Python
>         if val is not None:
>             ext = CompressCertificateExtension().create(val)
>             self.addExtension(ext)
> ```

we actually don't want those types of methods, the others are here because they've been here since before tls 1.2 was supported; new code should just look through extensions list by itself
___
*[`tlslite/messages.py` line 1324 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pEEh46fVTXzmzlZSJ:-O-pEEh51QK7HE546oQ_:b-2vdzkz) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/messages.py#L1324)):*
> ```Python
>             ext = CompressCertificateExtension().create(val)
>             self.addExtension(ext)
> ```

same here, no need to define property, `.extensions` are a public API
___
*[`tlslite/messages.py` line 2521 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pEk8J7RSNZyoI7VZB:-O-pEk8J7RSNZyoI7VZC:b-ysbapb) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60 [...]

2024-06-20 15:46 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: 1 of 23 files reviewed, 28 unresolved discussions (waiting on @tomato42)

___
*[`scripts/tls.py` line 81 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pIvN25KtdzfNaYJg2:-O-pKsO20_eqLNPHXClW:b-8hr65q) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/scripts/tls.py#L81)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

"Certificate Compression"?
</blockquote></details>

Maybe Compression Algorithms since it is loaded or not loaded. 
___
*[`tests/tlstest.py` line 2041 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pJghl-oManbtGfq6f:-O-pRIzEDyMvWZPI3xB1:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tests/tlstest.py#L2041)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

since client cert was not used here, we should also assert that the client side is None
and also add it to the client side of this test

similarly, we should add this assert to one of the tests that do use client certificates, to show that it is set for client certificates too
</blockquote></details>

Done.
___
*[`tests/tlstest.py` line 2082 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pJZJC01BL070Jnlon:-O-pRXo423qHKU2ozcT0:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tests/tlstest.py#L2082)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this should be HandshakeServer...
</blockquote></details>

Done.
___
*[`tlslite/constants.py` line 585 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pB-ndBpT_Pgwv3Vcs:-O-pTNa--UiGePbvb4s7:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/constants.py#L585)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

In the RFC it's a `CertificateCompressionAlgorithm`...
</blockquote></details>

Done.
___
*[`tlslite/constants.py` line 586 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pB2kmEFyP-KkLgC87:-O-pTYUg3FnBHbERKxPI:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/constants.py#L586)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

please add reference to the RFC here
</blockquote></details>

Done.
___
*[`tlslite/constants.py` line 591 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pAhno8AfAWiVIgLve:-O-pTlxK9_PoxT2wekm4:b-k452is) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/constants.py#L591)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

if you define `all` then you need to also re-declare `def toRepr` that that ignores it, see `ECPointFormat`
</blockquote></details>

We don't need an all-variable after all. I do not use it.
___
*[`tlslite/extensions.py` line 2161 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pBaBFCPhXKGVQV51h:-O-pUc2uDSJrNihdl7DA:bunki1k) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/extensions.py#L2161)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I don't think we need to shorten it, I think it can be the full `CertificateCompressionAlgorithmsExtension` (from struct name) or `CompressedCertificateExtension` (from the extension ID name)
</blockquote></details>

Changed it to `CompressedCertificateExtension`
___
*[`tlslite/handshakesettings.py` line 372 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pCDeS3DvR_ytzCXnU:-O-pUuYu89JuG9ijmu_A:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L372)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

should be `:ivar certificate_compression_send:`
</blockquote></details>

Done.
___
*[`tlslite/handshakesettings.py` line 378 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pCIsB96hynlHA8-BX:-O-pUurJ69fgEOJNd0ef:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L378)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

should be `:ivar certificate_compression_receive:`
</blockquote></details>

Done.
___
*[`tlslite/handshakesettings.py` line 640 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pCq1VEnk3T425uecT:-O-pVoTT99-I4pgfYpZa:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L640)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

err... I don't think we want to support string as the value, if the user wants to use a specific algorithm, they can set it to a tuple
</blockquote></details>

Done.
___
*[`tlslite/handshakesettings.py` line 644 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pD6z8EBZoKtVpfOKG:-O-pVpFm2uxLa89Kiq2w:b54ei3x) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L644)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

a `tuple` should also be accepted... :grin: 
in general we just need an iterable, as long as we can iterate over it, we're good, there's no need to do an explicit check for the tape
</blockquote></details>

Used hasattr(..., \_\_iter\_\_) to ensure that it is iterable
___
*[`tlslite/handshakesettings.py` line 659 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pDeGi-sgQnW2KfBLs:-O-pWDzz4gG1hceUQLKk:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L659)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here, no need for explicit check
</blockquote></details>

Done.
___
*[`tlslite/messages.py` line 556 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pDvT_5TNI4jHGK6Ft:-O-pgM53AVAoBd1LidzE:bb6un1j) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/messages.py#L556)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

we actually don't want those types of methods, the others are here because they've been here since before tls 1.2 was supported; new code should just look through extensions list by itself
</blockquote></details>

Done
___
*[`tlslite/messages.py` line 1324 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pEEh46fVTXzmzlZSJ:-O-q28YL3bqyOvSkIoHj:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/messages.py#L1324)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here, no need to define property, `.extensions` are a public API
</blockquote></details>

Done.
___
*[`tlslite/messages.py` line 2521 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pEk8J7RSNZyoI7VZB:-O-pgflF9VXnYej0AyY3:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/messages.py#L2521)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

please change this comment into an `assert`
</blockquote></details>

Done.
___
*[`tlslite/messages.py` line 2548 at r1](https://reviewable.io/r [...]

2024-06-20 15:46 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: 1 of 23 files reviewed, 28 unresolved discussions (waiting on @tomato42)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-p9CiH3fwnTIf4I0da):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

"Support for compressed_certificate extension"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-25 18:13 UTC, GeorgePantelakis commented
I think it is ready for another review!

2024-06-27 15:13 UTC, tomato42 requested changes
> Reviewed 1 of 23 files at r1, 6 of 14 files at r3, 18 of 18 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: all files reviewed, 16 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`.github/workflows/ci.yml` line 222 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3Et90wgeg6B1hKF9:-O0P3Et90wgeg6B1hKFA:b-5etaz2) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L222)):*
> ```YAML
>             os: ubuntu-latest
>             python-version: '3.12'
>             opt-deps: ['brotli', 'zstd']
> ```

first, please place above the `# finally test with multiple dependencies installed at the same time` line
second, please add the `brotli` and `zstd` deps to the runs with all dependencies
___
*[`.github/workflows/ci.yml` line 347 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3ZHNCTatvjTAPWrc:-O0P3ZHNCTatvjTAPWrd:bqwh8oc) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L347)):*
> ```YAML
>         run: pip install brotli
>       - name: Install zstandard for py3.8 and after
>         if: ${{ contains(matrix.opt-deps, 'zstd') && matrix.python-version != '2.7' && matrix.python-version != '3.6' && matrix.python-version != '3.7' }}
> ```

why do we need the check for versions here if we don't have it in the matrix above?
___
*[`.github/workflows/ci.yml` line 359 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3nbe5w0uQcigEB_9:-O0P3nbe5w0uQcigEB_A:b4new3z) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L359)):*
> ```YAML
>           wget https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz
>           wget https://files.pythonhosted.org/packages/a8/5a/5cf074e1c6681dcbb4e640113f58bed16955e7da9a6c8090b518031775e7/hypothesis-2.0.0.tar.gz
>           wget https://files.pythonhosted.org/packages/f8/86/410d53faff049641f34951843245d168261512aea787a1f9f05c3fa025a0/pylint-1.7.6-py2.py3-none-any.whl
> ```

why we have this in the diff?
___
*[`.github/workflows/ci.yml` line 385 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3rOW6jSTzu2j8e-D:-O0P3rOW6jSTzu2j8e-E:b-1t6k0o) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L385)):*
> ```YAML
>           wget https://files.pythonhosted.org/packages/c7/a3/c5da2a44c85bfbb6eebcfc1dde24933f8704441b98fdde6528f4831757a6/linecache2-1.0.0-py2.py3-none-any.whl
>           wget https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
>           wget https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
> ```

same here, why it's in the diff?
___
*[`scripts/tls.py` line 81 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pIvN25KtdzfNaYJg2:-O0P4XQ70RdcuQmiknZ4:b-xlgt4e) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/scripts/tls.py#L81)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Maybe Compression Algorithms since it is loaded or not loaded.
</blockquote></details>

there are multiple compression algorithms in TLS and HTTP, we really need to be precise here and specify we're talking about certificate compression algorithms
___
*[`tlslite/handshakesettings.py` line 644 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pD6z8EBZoKtVpfOKG:-O0P5Syt5qxKwgdVqC5H:bl28pr9) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L644)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Used hasattr(..., \_\_iter\_\_) to ensure that it is iterable
</blockquote></details>

that's not pythonic, in general the code should just try to do something instead of testing if it can do something before attempting it
___
*[`tlslite/handshakesettings.py` line 659 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pDeGi-sgQnW2KfBLs:-O0P5vwZDRl3SUxlIAGY:b-2guby3) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L659)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same here
___
*[`tlslite/tlsconnection.py` line 66 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P6rnpBC8hFaPFujkP:-O0P6rnpBC8hFaPFujkQ:b3j2eff) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L66)):*
> ```Python
>     :py:class:`~.integration.tlsasyncdispatchermixin.TLSAsyncDispatcherMixIn`).
> 
>     :vartype client_cert_compression_algo: string
> ```

the type is `str`
___
*[`tlslite/tlsconnection.py` line 68 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P6gwi-L0_UNmjrJOW:-O0P6gwi-L0_UNmjrJOX:bjf17x0) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L68)):*
> ```Python
>     :vartype client_cert_compression_algo: string
>     :ivar client_cert_compression_algo: Set to the compression algorithm used
>         for the compression of the server certificate. In the case of multiple
> ```

"server certificate"?
___
*[`tlslite/tlsconnection.py` line 73 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P6tpy2Xk9oxfDvJWk:-O0P6tpy2Xk9oxfDvJWl:b3j2eff) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L73)):*
> ```Python
>         used then it is set to None.
> 
>     :vartype server_cert_compression_algo: string
> ```

the type is `str`
___
*[`tlslite/tlsconnection.py` line 2535 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P7d3iBpATyFgxgmAi:-O0P7d3iBpATyFgxgmAj:b8epi6b) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L2535)):*
> ```Python
>                 algos_numbers = []
>             extensions.append(CompressedCertificateExtension().create(
>                 algos_numbers))
> ```

this will create a malformed extension, won't it ?
___
*[`tlslite/tlsrecordlayer.py` line 341 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pHuAD0o9N6NCuKE38:-O0P8Aov2VPYSoZAhNMy:b-qk6304) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/tlsrecordlayer.py#L341)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Yes, it is really ugly (looping through all the cert requests) but it is conditional. So goal was achieved (I think).
</blockquote></details>

yup, looks good
___
*[`tlslite/tlsrecordlayer.py` line 339 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P8IjdCvMEchXarIou:-O0P8IjdCvMEchXarIov:bnin785) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsrecordlayer.py#L339)):*
> ```Python
>             elif self._cert_requests:
>                 cert_req_with_comp_cert_ext = False
>                 for _, cert_request in self._cert_requests.items():
> ```

`_cert_requests.values()`?
___
*[`tlslite/utils/brotlidecpy/__init__.py` line 11 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pIX7_7jm9ARJ9cRU-:-O0PA4kxEryHovh87NRU:bdo9m99) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f [...]

2024-06-27 17:53 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: 20 of 28 files reviewed, 16 unresolved discussions (waiting on @tomato42)

___
*[`.github/workflows/ci.yml` line 222 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3Et90wgeg6B1hKF9:-O0Pib0h4_qnpQ-CY4YU:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L222)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

first, please place above the `# finally test with multiple dependencies installed at the same time` line
second, please add the `brotli` and `zstd` deps to the runs with all dependencies
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 347 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3ZHNCTatvjTAPWrc:-O0PibWbDaNGkUtasceh:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L347)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why do we need the check for versions here if we don't have it in the matrix above?
</blockquote></details>

Done.
___
*[`.github/workflows/ci.yml` line 359 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3nbe5w0uQcigEB_9:-O0PiTGeD7A3aH-jrCZ6:b-z2hr7p) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L359)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why we have this in the diff?
</blockquote></details>

spaces in the end that my IDE is removing automagically
___
*[`.github/workflows/ci.yml` line 385 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P3rOW6jSTzu2j8e-D:-O0PiaB2CI5oOH6gOkqt:b-z2hr7p) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/.github/workflows/ci.yml#L385)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here, why it's in the diff?
</blockquote></details>

spaces in the end that my IDE is removing automagically
___
*[`scripts/tls.py` line 81 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pIvN25KtdzfNaYJg2:-O0Pivh_7iApDjhg8nuN:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/scripts/tls.py#L81)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

there are multiple compression algorithms in TLS and HTTP, we really need to be precise here and specify we're talking about certificate compression algorithms
</blockquote></details>

Done.
___
*[`tlslite/handshakesettings.py` line 644 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pD6z8EBZoKtVpfOKG:-O0PjqLP6s79ih_vEsFh:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L644)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

that's not pythonic, in general the code should just try to do something instead of testing if it can do something before attempting it
</blockquote></details>

Done.
___
*[`tlslite/handshakesettings.py` line 659 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pDeGi-sgQnW2KfBLs:-O0PjqgvAw9MegDESGXO:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/handshakesettings.py#L659)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Done.
___
*[`tlslite/tlsconnection.py` line 66 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P6rnpBC8hFaPFujkP:-O0Pk2Y12D5VBZqS7cpN:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L66)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

the type is `str`
</blockquote></details>

Done.
___
*[`tlslite/tlsconnection.py` line 68 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P6gwi-L0_UNmjrJOW:-O0Pk2kR0WAywmMHWo8N:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L68)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

"server certificate"?
</blockquote></details>

Done.
___
*[`tlslite/tlsconnection.py` line 73 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P6tpy2Xk9oxfDvJWk:-O0Pk33g7Hft0qCfdh1B:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L73)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

the type is `str`
</blockquote></details>

Done.
___
*[`tlslite/tlsconnection.py` line 2535 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P7d3iBpATyFgxgmAi:-O0Po7ls1KoY_TuJTJ0U:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsconnection.py#L2535)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this will create a malformed extension, won't it ?
</blockquote></details>

Done.
___
*[`tlslite/tlsrecordlayer.py` line 339 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0P8IjdCvMEchXarIou:-O0Pk97g-vW-fhdPPL4V:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/tlslite/tlsrecordlayer.py#L339)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`_cert_requests.values()`?
</blockquote></details>

Done.
___
*[`tlslite/utils/brotlidecpy/__init__.py` line 11 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O-pIX7_7jm9ARJ9cRU-:-O0PkHut4njRxcMre_zL:b-w57r14) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/30b11d458f93060fa4fd60439658e81c8c10209f/tlslite/utils/brotlidecpy/__init__.py#L11)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

no, I'd rather use it, less issues with portability, but we need to follow the requirements of the LICENCE of the code we're adding
</blockquote></details>

What are the requirements? Do we need to do something else? I don't see something specific.
___
*[`unit_tests/test_tlslite_handshakesettings.py` line 497 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0PAmx76wP5mABF3jl1:-O0Plze89DCa1w6skySF:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/unit_tests/test_tlslite_handshakesettings.py#L497)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

those should be separate unit tests
</blockquote></details>

Done.
___
*[`unit_tests/test_tlslite_messages.py` line 4061 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0PEsgN9eLFDk40g5mp:-O0PlXKD1vcL6aqy6s3W:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/unit_tests/test_tlslite_messages.py#L4061)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

shouldn't it be "an"?
</blockquote></details>

Done.
___
*[`unit_tests/test_tlslite_utils_compression.py` line 35 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0PFB1DD8BGblh0JQi5:-O0PlSJg--kTzDwyZoZy:b31oay1) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/unit_tests/test_tlslite_utils_compression.py#L35)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

those should be separate unit tests
</blockqu [...]

2024-06-28 12:49 UTC, GeorgePantelakis reviewed
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: all files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[`unit_tests/test_tlslite_handshakesettings.py` line 509 at r6](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0ToJUC2BT_yqjw3_R4:-O0Tt0Af3Kbyw3SvO5c8:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/b66744f906b83a2947693462a259040076007cc1/unit_tests/test_tlslite_handshakesettings.py#L509)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this too should be in a separate unit test (in general, every `.validate()` call should be in separate unit test)
</blockquote></details>

Done.
___
*[`unit_tests/test_tlslite_utils_compression.py` line 35 at r4](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-O0PFB1DD8BGblh0JQi5:-O0Tt0mY4E90rdywHFIV:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/bd585eb891b3c97958f4cca9feb8dafad217058e/unit_tests/test_tlslite_utils_compression.py#L35)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

to make sure that we get all errors when the test cases are executed, not just the first failure
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-01 13:03 UTC, tomato42 approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)



<!-- Sent from Reviewable.io -->

2024-07-29 13:48 UTC, tomato42 approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)



<!-- Sent from Reviewable.io -->

2024-07-29 13:49 UTC, tomato42 submitted a review, later dismissed
the CI failures looks relevant

> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521#-:-O2yk3R39UvuikFReQSo:be69a7u)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)



<!-- Sent from Reviewable.io -->

2024-08-30 14:00 UTC, tomato42 approved these changes
> Reviewed 10 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/521)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)



<!-- Sent from Reviewable.io -->

2024-08-30 14:19 UTC, merged