publish wheels
tlsfuzzer/tlslite-ng pull request #534
Opened 2024-11-27 17:47 UTC by dimbleby

Direct invocation of setup.py [is deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/)

It is desirable to publish wheels.  Else everyone who installs your package has to build the wheel themselves: which is slower, and might conceivably go wrong.  

Better for package maintainers to build their wheels once and for all rather than make everyone else do it, every time.

2024-11-27 18:32 UTC, tomato42 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/534)* status: all files reviewed, 2 unresolved discussions (waiting on @dimbleby)

___
*[`Makefile` line 36 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/534#-OCisv-78iEDapFUmXkf:-OCisv-78iEDapFUmXkg:bmfn6d1) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/3b8016f8e455bf53dd966749cae8e92f3ceb6692/Makefile#L36)):*
> ```Makefile
> .PHONY : docs
> docs:
> 	python -m pip install -r docs/requirements.txt
> ```

Isn't this modifying local environment?!
I'm pretty sure that _building_ documentation shouldn't silently install packages
___
*[`Makefile` line 40 at r1](https://reviewable.io/reviews/tlsfuzzer/tlslite-ng/534#-OCitBEp00FtzJx6O94n:-OCitBEp00FtzJx6O94o:b9n4guz) ([raw file](https://github.com/tlsfuzzer/tlslite-ng/blob/3b8016f8e455bf53dd966749cae8e92f3ceb6692/Makefile#L40)):*
> ```Makefile
> 
> dist: docs
> 	python -m pip install build
> ```

why not just `python -m build`?


<!-- Sent from Reviewable.io -->

2024-11-27 18:42 UTC, dimbleby commented
it is not clear to me how you prefer to set up your virtual environment, feel free to make tweaks as you like.  What I am mostly  interested in encouraging is: please build (and publish) wheels as well as sdists.

but the `make docs` does not succeed unless you have installed the docs-requirements, and the `make dist` does not succeed unless you install the `build` package - so I think that my arrangement is reasonable

2024-11-27 20:13 UTC, tomato42 commented
> What I am mostly interested in encouraging is: please build (and publish) wheels as well as sdists.

sure, can do :slightly_smiling_face: 

> but the make docs does not succeed unless you have installed the docs-requirements, and the make dist does not succeed unless you install the build package - so I think that my arrangement is reasonable

well, I believe in the principle of least surprise: commands called "build" should not "install" packages

it's normal in other projects that `./configure` fails because you don't have dependencies installed, handling them is done through documentation, not trying to do it manually (maybe they want to install modules through their package manager, maybe they forgot to activate their virtual environment... too much guesswork)

2024-11-27 20:46 UTC, dimbleby commented
As I say, feel free to make rearrangements to suit your workflow.

There is more than one way to skin a cat, IMO using a makefile to install dependencies is absolutely fine, but I have no interest in persuading you to do something you want to do.

Please make whatever changes you like to this pull request.

2024-12-16 14:31 UTC, tomato42 commented
resolved in https://github.com/tlsfuzzer/tlslite-ng/pull/536

2024-12-16 14:31 UTC, closed without merging